import { NextRequest, NextResponse } from "next/server"
import { getAuthUser } from "@/lib/auth"
import { pool } from "@/lib/db"

// Deterministic, render-ready matches (generated by Puglit): each match includes the
// OTHER user's full item as `item`, so the UI never has to guess the response shape.
export async function GET(request: NextRequest) {
  const u = await getAuthUser(request)
  if (!u) return NextResponse.json({ error: "unauthorized" }, { status: 401 })
  const { rows } = await pool.query(
    `SELECT m.id AS id,
        to_json(i) AS item,
        (CASE WHEN m.user_a = $1 THEN m.user_b ELSE m.user_a END) AS other_user_id
     FROM matches m
     JOIN items i ON i.id IN (m.item_a, m.item_b) AND i.owner_id <> $1
     WHERE m.user_a = $1 OR m.user_b = $1
     ORDER BY m.id DESC`,
    [u.userId]
  )
  return NextResponse.json(rows)
}
