-- Promiedos — catalog seed (generated by Puglit's Data Ingestion agent).
-- Real-world reference data so the app works on first run; refresh via app/api/cron/refresh.

-- seed
INSERT INTO leagues (id, name, country, season, current_round) VALUES
(1, 'Liga Profesional de Fútbol', 'Argentina', '2023', 10),
(2, 'Primera Nacional', 'Argentina', '2023', 15);

INSERT INTO matches (id, date_time, team_home, team_away, score_home, score_away) VALUES
(1, NOW() - INTERVAL '1 day', 'River Plate', 'Boca Juniors', 2, 1),
(2, NOW(), 'Racing Club', 'Independiente', 0, 0),
(3, NOW() + INTERVAL '2 hours', 'San Lorenzo', 'Vélez Sarsfield', 1, 1),
(4, CURRENT_DATE + INTERVAL '1 day', 'Rosario Central', 'Newell''s Old Boys', 0, 0),
(5, CURRENT_DATE + INTERVAL '2 days', 'Estudiantes', 'Gimnasia', 0, 0);

INSERT INTO players (id, name, team, goals, position) VALUES
(1, 'Franco Armani', 'River Plate', 0, 'Goalkeeper'),
(2, 'Carlos Izquierdoz', 'Boca Juniors', 0, 'Defender'),
(3, 'Enzo Pérez', 'River Plate', 3, 'Midfielder'),
(4, 'Darío Benedetto', 'Boca Juniors', 5, 'Forward'),
(5, 'Lisandro López', 'Racing Club', 2, 'Defender'),
(6, 'Maximiliano Meza', 'Independiente', 4, 'Midfielder'),
(7, 'Ángel Romero', 'San Lorenzo', 6, 'Forward'),
(8, 'Lautaro Morales', 'Vélez Sarsfield', 0, 'Goalkeeper');

INSERT INTO fixtures (id, match_id, date, league_id, status) VALUES
(1, 1, CURRENT_DATE - INTERVAL '1 day', 1, 'Completed'),
(2, 2, CURRENT_DATE, 1, 'Ongoing'),
(3, 3, CURRENT_DATE, 1, 'Scheduled'),
(4, 4, CURRENT_DATE + INTERVAL '1 day', 1, 'Scheduled'),
(5, 5, CURRENT_DATE + INTERVAL '2 days', 2, 'Scheduled');

