/**
 * Puglit web — jobs.ts
 * A generation JOB = the multi-agent build pipeline, tracked step by step so the
 * user gets a live progress URL. Each step is advanced by one /api/job/[id]/advance
 * call (serverless-friendly: short calls, client polls until done). Reuses the
 * existing generators + adds SQL migrations and an ER diagram as artifacts.
 */
import { randomBytes } from "node:crypto"
import { query, isConfigured, saveProject } from "@/lib/db"
import { generateConfig, slugify, type IntakeAnswers } from "@/lib/generate"
import { applyBranding } from "@/lib/branding"
import { designEntities } from "@/lib/entitygen"
import { generateLogoSvg } from "@/lib/logo-gen"
import { generateLandingHtml } from "@/lib/landing-gen"
import { assembleProject, githubConfigured } from "@/lib/github"
import { runContracts, genVerifiedEngine } from "@/lib/agents"
import { genTechnicalDocs, genBusinessDocs } from "@/lib/docs"
import type { DomainConfig, Entity, FieldType } from "@/lib/domain-types"

export type StepStatus = "pending" | "running" | "done" | "error"
export interface Step { key: string; label: string; status: StepStatus; detail?: string; startedAt?: string; finishedAt?: string; attempts?: number }

// Safety rails
const CONCURRENCY = 2          // max jobs running at once (queue the rest)
const STEP_TIMEOUT_MS = 120_000 // a "running" step older than this is considered stuck
const MAX_ATTEMPTS = 3         // per-step retries before marking it errored
const LEASE_MS = 100_000       // lock window while a step is being advanced

// The "agents" / phases. TodoAstros-grade baseline is assembled from the spine;
// the domain-specific parts are generated.
// The "agents". Aligned to the TodoAstros standard (STANDARD.md). Each is marked
// honestly: GENERATED per product, ASSEMBLED from the spine baseline, or SCAFFOLD
// (wired as a placeholder to be completed).
const PLAN: { key: string; label: string }[] = [
  { key: "data-model", label: "Arquitecto · modelo de datos" },
  { key: "contracts", label: "Contracts · tipos + contrato de API" },
  { key: "brand", label: "Marca · logo + paleta" },
  { key: "design", label: "Diseño · landing" },
  { key: "schema", label: "DBA · esquema SQL + migraciones" },
  { key: "seed", label: "DBA · datos de ejemplo (seed)" },
  { key: "erd", label: "Arquitecto · diagrama ER (UML)" },
  { key: "auth", label: "Auth · cuentas, JWT, magic-link (spine)" },
  { key: "payments", label: "Pagos · Stripe + gating (scaffold)" },
  { key: "email", label: "Email · Resend + lifecycle (spine)" },
  { key: "crons", label: "Crons · fire-and-forget (scaffold)" },
  { key: "admin", label: "Admin · panel (scaffold)" },
  { key: "dashboard", label: "Frontend · dashboard del cliente (spine)" },
  { key: "analytics", label: "Analytics · funnels + A/B (spine)" },
  { key: "seo", label: "SEO · metadata + sitemap (scaffold)" },
  { key: "security", label: "Seguridad · RLS, rate-limit, headers (spine)" },
  { key: "engine", label: "Engine · lógica única del producto (plan)" },
  { key: "docs-tech", label: "Technical Writer · docs técnica + UML" },
  { key: "docs-biz", label: "Business Strategist · FODA, Lean, pitch deck (YC)" },
  { key: "env", label: "DevOps · .env + integraciones" },
  { key: "deliver", label: "DevOps · push del repo a GitHub" },
]

function genEnvExample(creds: any): string {
  const c = creds || {}
  return `# Generated by Puglit. Fill the blanks; set SECRETS in your deploy env (do NOT commit them).
# DB — use the Supabase Supavisor POOLER (IPv4), never db.<ref>.supabase.co (IPv6-only).
POSTGRES_HOST=aws-1-<region>.pooler.supabase.com
POSTGRES_PORT=5432
POSTGRES_USER=postgres.<projectref>
POSTGRES_PASSWORD=
POSTGRES_DB=postgres
JWT_SECRET=
APP_URL=http://localhost:3000
# Email
RESEND_API_KEY=
# Payments
STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=
# AI
OPENAI_API_KEY=
# Crons
CRON_SECRET=
# Public analytics (safe in client) — prefilled from your input
NEXT_PUBLIC_SUPABASE_URL=${c.supabaseUrl || ""}
NEXT_PUBLIC_GA_ID=${c.gaId || ""}
NEXT_PUBLIC_CLARITY_ID=${c.clarityId || ""}
# Observability
SENTRY_DSN=
`
}

const SAMPLE: Record<string, string> = { text: "'Ejemplo'", longtext: "'Texto de ejemplo'", int: "1", float: "1.0", bool: "true", date: "CURRENT_DATE", datetime: "NOW()", json: "'{}'::jsonb", enum: "'a'", ref: "1", money: "9.99", slug: "'ejemplo'", url: "'https://example.com'", email: "'demo@example.com'" }
function genSeed(entities: Entity[]): string {
  return entities.map((e) => {
    const t = (e.plural || e.name).toLowerCase().replace(/[^a-z0-9]+/g, "_")
    const cols = e.fields.map((f) => f.name)
    const vals = e.fields.map((f) => SAMPLE[f.type] || "'x'")
    if (!cols.length) return ""
    return `INSERT INTO ${t} (${cols.join(", ")}) VALUES\n  (${vals.join(", ")});`
  }).filter(Boolean).join("\n\n")
}

const SQL_TYPE: Record<FieldType, string> = {
  text: "TEXT", longtext: "TEXT", int: "INTEGER", float: "DOUBLE PRECISION", bool: "BOOLEAN",
  date: "DATE", datetime: "TIMESTAMPTZ", json: "JSONB", enum: "TEXT", ref: "INTEGER",
  money: "NUMERIC(12,2)", slug: "VARCHAR(160)", url: "TEXT", email: "VARCHAR(255)",
}
const tbl = (e: Entity) => (e.plural || e.name).toLowerCase().replace(/[^a-z0-9]+/g, "_")

export function genSql(entities: Entity[]): string {
  return entities.map((e) => {
    const cols = ["  id BIGSERIAL PRIMARY KEY"]
    if (e.ownedByUser) cols.push("  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE")
    for (const f of e.fields) cols.push(`  ${f.name} ${SQL_TYPE[f.type] || "TEXT"}${f.required ? " NOT NULL" : ""}${f.unique ? " UNIQUE" : ""}`)
    cols.push("  created_at TIMESTAMPTZ DEFAULT NOW()")
    return `CREATE TABLE IF NOT EXISTS ${tbl(e)} (\n${cols.join(",\n")}\n);`
  }).join("\n\n")
}

export function genErd(entities: Entity[]): string {
  const lines = ["erDiagram"]
  for (const e of entities) {
    lines.push(`  ${e.name} {`)
    for (const f of e.fields) lines.push(`    ${(SQL_TYPE[f.type] || "TEXT").split("(")[0].toLowerCase()} ${f.name}`)
    lines.push("  }")
  }
  for (const e of entities) for (const f of e.fields) if (f.type === "ref" && f.ref) lines.push(`  ${e.name} }o--|| ${f.ref} : "${f.name}"`)
  return lines.join("\n")
}

interface JobRow { id: string; slug: string; name: string; email: string | null; status: string; answers: any; branding: any; config: DomainConfig | null; steps: Step[]; artifacts: any; completion?: number; error?: string }

export async function createJob(input: { answers: IntakeAnswers; branding: any; chosenLanding?: string; creds?: any }): Promise<string> {
  const id = randomBytes(8).toString("hex")
  let slug = slugify(input.answers.name)
  const { rows } = await query(`SELECT 1 FROM puglit_projects WHERE slug=$1`, [slug]).catch(() => ({ rows: [] as any[] }))
  if (rows.length) slug = `${slug}-${randomBytes(2).toString("hex")}`
  const steps: Step[] = PLAN.map((p) => ({ ...p, status: "pending" as StepStatus, attempts: 0 }))
  // New jobs start QUEUED — the scheduler promotes them to running under the cap.
  await query(
    `INSERT INTO puglit_jobs (id, slug, name, email, status, answers, branding, config, steps, artifacts, completion)
     VALUES ($1,$2,$3,$4,'queued',$5,$6,$7,$8,$9,0)`,
    [id, slug, input.answers.name, input.answers.email || null, JSON.stringify(input.answers), JSON.stringify(input.branding || null), null, JSON.stringify(steps), JSON.stringify({ chosenLanding: input.chosenLanding || null, creds: input.creds || null })]
  )
  return id
}

/** Promote queued jobs to running while under the global concurrency cap. */
export async function promoteQueued(): Promise<void> {
  const { rows } = await query(`SELECT count(*)::int AS n FROM puglit_jobs WHERE status='running'`)
  let slots = CONCURRENCY - (rows[0]?.n || 0)
  if (slots <= 0) return
  const q = await query(`SELECT id FROM puglit_jobs WHERE status='queued' ORDER BY created_at ASC LIMIT $1`, [slots])
  for (const r of q.rows) await query(`UPDATE puglit_jobs SET status='running', updated_at=NOW() WHERE id=$1 AND status='queued'`, [r.id])
}

export async function getJob(id: string): Promise<JobRow | null> {
  if (!isConfigured()) return null
  const { rows } = await query(`SELECT * FROM puglit_jobs WHERE id=$1`, [id])
  return rows[0] || null
}

async function persist(job: JobRow, releaseLease = false) {
  const total = job.steps.length || 1
  const completion = Math.round((job.steps.filter((s) => s.status === "done").length / total) * 100)
  await query(`UPDATE puglit_jobs SET status=$2, config=$3, steps=$4, artifacts=$5, completion=$6, error=$7${releaseLease ? ", lease_until=NULL" : ""}, updated_at=NOW() WHERE id=$1`,
    [job.id, job.status, job.config ? JSON.stringify(job.config) : null, JSON.stringify(job.steps), JSON.stringify(job.artifacts), completion, job.error || null])
}

/** Try to acquire the per-job lease (lock). Returns true if we own it. */
async function acquireLease(id: string): Promise<boolean> {
  const { rows } = await query(
    `UPDATE puglit_jobs SET lease_until = NOW() + INTERVAL '${Math.round(LEASE_MS / 1000)} seconds'
     WHERE id=$1 AND (lease_until IS NULL OR lease_until < NOW()) RETURNING id`, [id])
  return rows.length > 0
}

export async function advanceJob(id: string): Promise<JobRow | null> {
  let job = await getJob(id)
  if (!job) return job
  if (job.status === "queued") { await promoteQueued(); job = await getJob(id); if (!job || job.status !== "running") return job }
  if (job.status !== "running") return job
  // lock: the poller and the sweeper must not advance the same job at once
  if (!(await acquireLease(id))) return job
  job = (await getJob(id)) as JobRow
  const step = job.steps.find((s) => s.status === "pending")
  if (!step) { job.status = "done"; await persist(job, true); return job }

  step.status = "running"; step.startedAt = new Date().toISOString(); step.attempts = (step.attempts || 0) + 1
  await persist(job)
  try {
    const A = job.answers as IntakeAnswers
    job.artifacts = job.artifacts || {}
    switch (step.key) {
      case "data-model": {
        const config = applyBranding(generateConfig(A), job.branding)
        const ents = await designEntities({ name: A.name, what: A.what, benefits: A.benefits })
        if (ents?.length) config.entities = ents
        job.config = config
        step.detail = (config.entities || []).map((e) => e.name).join(", ")
        break
      }
      case "brand": {
        if (job.config && !job.config.identity.logoSvg) {
          const svg = await generateLogoSvg(job.config)
          if (svg) job.config.identity.logoSvg = svg
        }
        step.detail = `Color ${job.config?.identity.brandColor}` + (job.config?.identity.logoSvg ? " · logo SVG" : "")
        break
      }
      case "design": {
        const chosen = job.artifacts.chosenLanding
        job.artifacts.landingHtml = (typeof chosen === "string" && chosen.length > 100) ? chosen : (job.config ? await generateLandingHtml(job.config) : null)
        step.detail = job.artifacts.landingHtml ? `${Math.round(job.artifacts.landingHtml.length / 1024)} KB` : "—"
        break
      }
      case "schema": {
        job.artifacts.sql = genSql(job.config?.entities || [])
        step.detail = `${(job.config?.entities || []).length} tablas`
        break
      }
      case "erd": {
        job.artifacts.erd = genErd(job.config?.entities || [])
        step.detail = "diagrama ER (Mermaid)"
        break
      }
      case "seed": { job.artifacts.seedSql = genSeed(job.config?.entities || []); step.detail = "INSERTs de ejemplo"; break }
      case "auth": step.detail = "JWT (web+móvil), magic-link, verificación, reset — del spine"; break
      case "payments": step.detail = "Stripe subs + webhooks + getEffectivePlan gating — scaffold listo para tus keys"; break
      case "email": step.detail = "Resend + email-logger + bounce poller — del spine"; break
      case "crons": step.detail = "app/api/cron/* fire-and-forget + CRON_SECRET — scaffold"; break
      case "admin": step.detail = "Panel admin gateado — scaffold"; break
      case "dashboard": step.detail = "Dashboard /app con CRUD de tus entidades — del spine"; break
      case "analytics": step.detail = "page_visits + analytics_events + /api/track + A/B — del spine"; break
      case "seo": step.detail = "metadata + sitemap + JSON-LD — scaffold"; break
      case "security": step.detail = "RLS, rate-limit map, security headers, validación — del spine"; break
      case "contracts": {
        if (job.config) job.artifacts.contracts = await runContracts(job.config)
        step.detail = job.artifacts.contracts ? "tipos + contrato de API definidos" : "—"
        break
      }
      case "engine": {
        // Real generate → verify → repair loop (control plane: only BLOCKING findings
        // trigger repair; capped iterations). Produces real code for the bespoke 20%.
        if (job.config) {
          const r = await genVerifiedEngine(job.config, job.artifacts.contracts || "")
          if (r) {
            job.artifacts.engine = { path: r.path, code: r.code }
            job.artifacts.findings = r.findings
            const block = r.findings.filter((f) => f.severity === "BLOCKING").length
            const adv = r.findings.filter((f) => f.severity === "ADVISORY").length
            step.detail = `${r.path} · ${r.iterations} iteración(es) · ${block} blocking abiertos · ${adv} advisory diferidos`
          } else step.detail = "—"
        }
        break
      }
      case "docs-tech": {
        if (job.config) job.artifacts.techDocs = await genTechnicalDocs(job.config, job.artifacts.contracts || "", job.artifacts.erd || "")
        step.detail = `${(job.artifacts.techDocs || []).length} docs técnicos`
        break
      }
      case "docs-biz": {
        if (job.config) job.artifacts.bizDocs = await genBusinessDocs(job.config)
        const n = (job.artifacts.bizDocs || []).length
        const deck = (job.artifacts.bizDocs || []).some((f: any) => f.path.endsWith(".html"))
        step.detail = `${n} docs de negocio${deck ? " + pitch deck" : ""}`
        break
      }
      case "env": { job.artifacts.envFile = genEnvExample(job.artifacts.creds); step.detail = "(.env.example + analytics cableado)"; break }
      case "deliver": {
        if (job.config) {
          await saveProject({ slug: job.slug, email: job.email, name: job.name, answers: A as any, config: job.config, landingHtml: job.artifacts.landingHtml })
          if (githubConfigured()) {
            const f = job.artifacts.findings || []
            const report = `# Build report — ${job.name}\n\n## Findings (control plane)\n\n### BLOCKING (resolved before ship)\n${f.filter((x: any) => x.severity === "BLOCKING").map((x: any) => "- " + x.desc).join("\n") || "- none"}\n\n### ADVISORY (deferred to backlog)\n${f.filter((x: any) => x.severity === "ADVISORY").map((x: any) => "- " + x.desc).join("\n") || "- none"}\n`
            const extraFiles = [
              { path: ".env.example", content: job.artifacts.envFile || genEnvExample(job.artifacts.creds) },
              { path: "sql/schema.sql", content: job.artifacts.sql || "" },
              { path: "sql/seed.sql", content: job.artifacts.seedSql || "" },
              { path: "docs/ER-DIAGRAM.md", content: "```mermaid\n" + (job.artifacts.erd || "") + "\n```" },
              { path: "docs/CONTRACTS.md", content: job.artifacts.contracts || "" },
              { path: "docs/BUILD_REPORT.md", content: report },
              ...(job.artifacts.engine?.path ? [{ path: job.artifacts.engine.path, content: job.artifacts.engine.code }] : []),
              ...((job.artifacts.techDocs || []) as { path: string; content: string }[]),
              ...((job.artifacts.bizDocs || []) as { path: string; content: string }[]),
            ].filter((f) => f.content)
            const built = await assembleProject({ slug: job.slug, name: job.name, configTs: configToTs(job.config), readme: `# ${job.name}\n\nGenerated by Puglit. See docs/ for the ER diagram and feature plan; sql/ for migrations + seed; .env.example for setup.`, extraFiles })
            job.artifacts.githubUrl = built.url
          }
          job.artifacts.previewUrl = `/x/${job.slug}`
        }
        break
      }
    }
    step.status = "done"; step.finishedAt = new Date().toISOString()
    if (!job.steps.some((s) => s.status === "pending")) {
      job.status = "done"
      await sendDoneEmail(job)
    }
  } catch (e) {
    const msg = (e as Error).message.slice(0, 140)
    if ((step.attempts || 0) < MAX_ATTEMPTS) { step.status = "pending"; step.detail = `reintento ${step.attempts}/${MAX_ATTEMPTS}: ${msg}` }
    else { step.status = "error"; step.detail = msg; job.status = "error"; job.error = `${step.key}: ${msg}` }
  }
  await persist(job, true) // release the lease
  return job
}

/** Watchdog: promote queued, recover stuck steps, and continue running jobs even
 *  if nobody has the build page open. Meant to be hit by a cron every minute. */
export async function sweep(): Promise<{ promoted: boolean; advanced: string[]; recovered: number }> {
  await promoteQueued()
  let recovered = 0
  // recover stuck "running" steps (lease expired + step started too long ago)
  const stuck = await query(
    `SELECT id, steps FROM puglit_jobs WHERE status='running' AND (lease_until IS NULL OR lease_until < NOW())`)
  for (const row of stuck.rows) {
    const steps: Step[] = row.steps
    let changed = false
    for (const s of steps) {
      if (s.status === "running" && s.startedAt && Date.now() - new Date(s.startedAt).getTime() > STEP_TIMEOUT_MS) {
        if ((s.attempts || 0) < MAX_ATTEMPTS) { s.status = "pending"; s.detail = "recuperado (estaba trabado)" }
        else { s.status = "error" }
        changed = true; recovered++
      }
    }
    if (changed) await query(`UPDATE puglit_jobs SET steps=$2, updated_at=NOW() WHERE id=$1`, [row.id, JSON.stringify(steps)])
  }
  // advance each running job by one step (drives jobs forward headlessly)
  const running = await query(`SELECT id FROM puglit_jobs WHERE status='running' ORDER BY updated_at ASC LIMIT $1`, [CONCURRENCY])
  const advanced: string[] = []
  for (const r of running.rows) { await advanceJob(r.id); advanced.push(r.id) }
  return { promoted: true, advanced, recovered }
}

function configToTs(config: DomainConfig): string {
  return `export * from "./domain-types"\nimport type { DomainConfig } from "./domain-types"\nconst config: DomainConfig = ${JSON.stringify(config, null, 2)}\nexport default config\n`
}

async function sendDoneEmail(job: JobRow) {
  const key = process.env.RESEND_API_KEY
  if (!key || !job.email) return
  const base = process.env.APP_URL || "https://puglit-home.vercel.app"
  try {
    await fetch("https://api.resend.com/emails", {
      method: "POST", headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        from: process.env.WAITLIST_FROM || "Puglit <onboarding@resend.dev>", to: job.email,
        subject: `🐶 ${job.name} está listo`,
        html: `<p>Tu proyecto <b>${job.name}</b> está listo.</p><p><a href="${base}/build/${job.id}">Ver el build</a> · <a href="${base}${job.artifacts?.previewUrl || ""}">Preview</a>${job.artifacts?.githubUrl ? ` · <a href="${job.artifacts.githubUrl}">Código</a>` : ""}</p>`,
      }),
    })
  } catch { /* email optional */ }
}
