/**
 * Puglit web — jobs.ts
 * A generation JOB = the multi-agent build pipeline, tracked step by step so the
 * user gets a live progress URL. Each step is advanced by one /api/job/[id]/advance
 * call (serverless-friendly: short calls, client polls until done). Reuses the
 * existing generators + adds SQL migrations and an ER diagram as artifacts.
 */
import { randomBytes } from "node:crypto"
import { query, isConfigured, saveProject } from "@/lib/db"
import { generateConfig, slugify, type IntakeAnswers } from "@/lib/generate"
import { applyBranding } from "@/lib/branding"
import { designEntities } from "@/lib/entitygen"
import { generateLogoSvg } from "@/lib/logo-gen"
import { generateBrandLogo } from "@/lib/art-director"
import { generateLandingHtml } from "@/lib/landing-gen"
import { assembleProject, githubConfigured } from "@/lib/github"
import { runContracts } from "@/lib/agents"
import { buildAdvance, initEngineState, initEngineStateWith, researchProduct, studyReference } from "@/lib/app-builder"
import { gameAdvance, initGameState, looksLikeGame } from "@/lib/game-builder"
import { stakeholderAdvance, initStakeholderState } from "@/lib/stakeholder"
import { harnessFiles } from "@/lib/harness"
import { genTechnicalDocs, genBusinessDocs } from "@/lib/docs"
import { dispatchCi, latestRun, getRun, runErrors, fixFiles, type CiError } from "@/lib/ci"
import type { DomainConfig, Entity, FieldType } from "@/lib/domain-types"

export type StepStatus = "pending" | "running" | "done" | "error"
export interface Step { key: string; label: string; status: StepStatus; detail?: string; startedAt?: string; finishedAt?: string; attempts?: number }

// Safety rails
const CONCURRENCY = 6          // max jobs running at once (queue the rest) — headroom so a fresh job isn't blocked by stale ones
const STEP_TIMEOUT_MS = 120_000 // a "running" step older than this is considered stuck
const MAX_ATTEMPTS = 3         // per-step retries before marking it errored
const LEASE_MS = 100_000       // lock window while a step is being advanced
const LIVE_MS = 300_000        // a "running" job occupies a slot only if updated this recently
const CI_STEP_TIMEOUT_MS = 900_000 // ci-verify polls real CI for minutes — far longer leash

// The "agents" / phases. TodoAstros-grade baseline is assembled from the spine;
// the domain-specific parts are generated.
// The "agents". Aligned to the TodoAstros standard (STANDARD.md). Each is marked
// honestly: GENERATED per product, ASSEMBLED from the spine baseline, or SCAFFOLD
// (wired as a placeholder to be completed).
const PLAN: { key: string; label: string }[] = [
  { key: "data-model", label: "Arquitecto · modelo de datos" },
  { key: "research", label: "Researcher · fuentes de datos reales" },
  { key: "contracts", label: "Contracts · tipos + contrato de API" },
  { key: "brand", label: "Marca · logo + paleta" },
  { key: "design", label: "Diseño · landing" },
  { key: "schema", label: "DBA · esquema SQL + migraciones" },
  { key: "seed", label: "DBA · datos de ejemplo (seed)" },
  { key: "erd", label: "Arquitecto · diagrama ER (UML)" },
  { key: "auth", label: "Auth · cuentas, JWT, magic-link (spine)" },
  { key: "payments", label: "Pagos · Stripe + gating (scaffold)" },
  { key: "email", label: "Email · Resend + lifecycle (spine)" },
  { key: "crons", label: "Crons · fire-and-forget (scaffold)" },
  { key: "admin", label: "Admin · panel (scaffold)" },
  { key: "dashboard", label: "Frontend · dashboard del cliente (spine)" },
  { key: "analytics", label: "Analytics · funnels + A/B (spine)" },
  { key: "seo", label: "SEO · metadata + sitemap (scaffold)" },
  { key: "security", label: "Seguridad · RLS, rate-limit, headers (spine)" },
  { key: "engine", label: "Engine · lógica única del producto (plan)" },
  { key: "stakeholder", label: "Stakeholder · 4 especialistas × 3 supervisiones" },
  { key: "docs-tech", label: "Technical Writer · docs técnica + UML" },
  { key: "docs-biz", label: "Business Strategist · FODA, Lean, pitch deck (YC)" },
  { key: "env", label: "DevOps · .env + integraciones" },
  { key: "deliver", label: "DevOps · push del repo a GitHub" },
  { key: "ci-verify", label: "QA · compilación real (CI) + auto-reparación" },
]
const MAX_CI = 3 // CI fix→re-verify cycles before shipping with a report

function genEnvExample(creds: any): string {
  const c = creds || {}
  return `# Generated by Puglit. Fill the blanks; set SECRETS in your deploy env (do NOT commit them).
# DB — use the Supabase Supavisor POOLER (IPv4), never db.<ref>.supabase.co (IPv6-only).
POSTGRES_HOST=aws-1-<region>.pooler.supabase.com
POSTGRES_PORT=5432
POSTGRES_USER=postgres.<projectref>
POSTGRES_PASSWORD=
POSTGRES_DB=postgres
JWT_SECRET=
APP_URL=http://localhost:3000
# Email
RESEND_API_KEY=
# Payments
STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=
# AI
OPENAI_API_KEY=
# Crons
CRON_SECRET=
# Public analytics (safe in client) — prefilled from your input
NEXT_PUBLIC_SUPABASE_URL=${c.supabaseUrl || ""}
NEXT_PUBLIC_GA_ID=${c.gaId || ""}
NEXT_PUBLIC_CLARITY_ID=${c.clarityId || ""}
# Observability
SENTRY_DSN=
`
}

const SAMPLE: Record<string, string> = { text: "'Ejemplo'", longtext: "'Texto de ejemplo'", int: "1", float: "1.0", bool: "true", date: "CURRENT_DATE", datetime: "NOW()", json: "'{}'::jsonb", enum: "'a'", ref: "1", money: "9.99", slug: "'ejemplo'", url: "'https://example.com'", email: "'demo@example.com'" }
function genSeed(entities: Entity[]): string {
  return entities.map((e) => {
    const t = (e.plural || e.name).toLowerCase().replace(/[^a-z0-9]+/g, "_")
    const cols = e.fields.map((f) => f.name)
    const vals = e.fields.map((f) => SAMPLE[f.type] || "'x'")
    if (!cols.length) return ""
    return `INSERT INTO ${t} (${cols.join(", ")}) VALUES\n  (${vals.join(", ")});`
  }).filter(Boolean).join("\n\n")
}

const SQL_TYPE: Record<FieldType, string> = {
  text: "TEXT", longtext: "TEXT", int: "INTEGER", float: "DOUBLE PRECISION", bool: "BOOLEAN",
  date: "DATE", datetime: "TIMESTAMPTZ", json: "JSONB", enum: "TEXT", ref: "INTEGER",
  money: "NUMERIC(12,2)", slug: "VARCHAR(160)", url: "TEXT", email: "VARCHAR(255)",
}
const tbl = (e: Entity) => (e.plural || e.name).toLowerCase().replace(/[^a-z0-9]+/g, "_")

export function genSql(entities: Entity[]): string {
  return entities.map((e) => {
    const cols = ["  id BIGSERIAL PRIMARY KEY"]
    if (e.ownedByUser) cols.push("  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE")
    for (const f of e.fields) cols.push(`  ${f.name} ${SQL_TYPE[f.type] || "TEXT"}${f.required ? " NOT NULL" : ""}${f.unique ? " UNIQUE" : ""}`)
    cols.push("  created_at TIMESTAMPTZ DEFAULT NOW()")
    return `CREATE TABLE IF NOT EXISTS ${tbl(e)} (\n${cols.join(",\n")}\n);`
  }).join("\n\n")
}

export function genErd(entities: Entity[]): string {
  const lines = ["erDiagram"]
  for (const e of entities) {
    lines.push(`  ${e.name} {`)
    for (const f of e.fields) lines.push(`    ${(SQL_TYPE[f.type] || "TEXT").split("(")[0].toLowerCase()} ${f.name}`)
    lines.push("  }")
  }
  for (const e of entities) for (const f of e.fields) if (f.type === "ref" && f.ref) lines.push(`  ${e.name} }o--|| ${f.ref} : "${f.name}"`)
  return lines.join("\n")
}

interface JobRow { id: string; slug: string; name: string; email: string | null; status: string; answers: any; branding: any; config: DomainConfig | null; steps: Step[]; artifacts: any; completion?: number; error?: string }

export async function createJob(input: { answers: IntakeAnswers; branding: any; chosenLanding?: string; creds?: any; winnerBlueprint?: any }): Promise<string> {
  const id = randomBytes(8).toString("hex")
  let slug = slugify(input.answers.name)
  const { rows } = await query(`SELECT 1 FROM puglit_projects WHERE slug=$1`, [slug]).catch(() => ({ rows: [] as any[] }))
  if (rows.length) slug = `${slug}-${randomBytes(2).toString("hex")}`
  const steps: Step[] = PLAN.map((p) => ({ ...p, status: "pending" as StepStatus, attempts: 0 }))
  // New jobs start QUEUED — the scheduler promotes them to running under the cap.
  await query(
    `INSERT INTO puglit_jobs (id, slug, name, email, status, answers, branding, config, steps, artifacts, completion)
     VALUES ($1,$2,$3,$4,'queued',$5,$6,$7,$8,$9,0)`,
    [id, slug, input.answers.name, input.answers.email || null, JSON.stringify(input.answers), JSON.stringify(input.branding || null), null, JSON.stringify(steps), JSON.stringify({ chosenLanding: input.chosenLanding || null, creds: input.creds || null, winnerBlueprint: input.winnerBlueprint || null })]
  )
  return id
}

/** Promote queued jobs to running while under the global concurrency cap. */
export async function promoteQueued(): Promise<void> {
  // Count only LIVE running jobs: a job orphaned (tab closed + no cron) goes stale
  // and must not jam the queue forever. Stale running jobs free their slot.
  const { rows } = await query(`SELECT count(*)::int AS n FROM puglit_jobs WHERE status='running' AND updated_at > NOW() - INTERVAL '${Math.round(LIVE_MS / 1000)} seconds'`)
  let slots = CONCURRENCY - (rows[0]?.n || 0)
  if (slots <= 0) return
  const q = await query(`SELECT id FROM puglit_jobs WHERE status='queued' ORDER BY created_at ASC LIMIT $1`, [slots])
  for (const r of q.rows) await query(`UPDATE puglit_jobs SET status='running', updated_at=NOW() WHERE id=$1 AND status='queued'`, [r.id])
}

export async function getJob(id: string): Promise<JobRow | null> {
  if (!isConfigured()) return null
  const { rows } = await query(`SELECT * FROM puglit_jobs WHERE id=$1`, [id])
  return rows[0] || null
}

async function persist(job: JobRow, releaseLease = false) {
  const total = job.steps.length || 1
  const completion = Math.round((job.steps.filter((s) => s.status === "done").length / total) * 100)
  await query(`UPDATE puglit_jobs SET status=$2, config=$3, steps=$4, artifacts=$5, completion=$6, error=$7${releaseLease ? ", lease_until=NULL" : ""}, updated_at=NOW() WHERE id=$1`,
    [job.id, job.status, job.config ? JSON.stringify(job.config) : null, JSON.stringify(job.steps), JSON.stringify(job.artifacts), completion, job.error || null])
}

/** Try to acquire the per-job lease (lock). Returns true if we own it. */
async function acquireLease(id: string): Promise<boolean> {
  const { rows } = await query(
    `UPDATE puglit_jobs SET lease_until = NOW() + INTERVAL '${Math.round(LEASE_MS / 1000)} seconds'
     WHERE id=$1 AND (lease_until IS NULL OR lease_until < NOW()) RETURNING id`, [id])
  return rows.length > 0
}

export async function advanceJob(id: string): Promise<JobRow | null> {
  let job = await getJob(id)
  if (!job) return job
  if (job.status === "queued") { await promoteQueued(); job = await getJob(id); if (!job || job.status !== "running") return job }
  if (job.status !== "running") return job
  // lock: the poller and the sweeper must not advance the same job at once
  if (!(await acquireLease(id))) return job
  job = (await getJob(id)) as JobRow
  const reentrant = job.steps.find((s) => s.status === "running" && (s.key === "ci-verify" || s.key === "engine" || s.key === "stakeholder"))
  const step = reentrant || job.steps.find((s) => s.status === "pending")
  if (!step) { job.status = "done"; await persist(job, true); return job }

  // ci-verify is RE-ENTRANT: it polls the real CI across calls (no retry burn).
  if (step.key === "ci-verify") {
    try { await handleCiVerify(job, step) } catch (e) { step.status = "done"; step.detail = "CI omitido: " + (e as Error).message.slice(0, 80) }
    if (job.status === "running" && !job.steps.some((s) => s.status === "pending" || (s.status === "running" && s.key === "ci-verify"))) { job.status = "done"; await sendDoneEmail(job) }
    await persist(job, true)
    return job
  }

  // engine is RE-ENTRANT: the full app build is long, so we advance ONE bounded unit
  // (plan / one route / one page / finalize) per call and resume from persisted state —
  // this is what makes a real (multi-minute) build COMPLETE on serverless instead of
  // timing out and shipping an empty spine.
  if (step.key === "engine") {
    step.status = "running"; step.startedAt = new Date().toISOString(); job.artifacts = job.artifacts || {}
    try {
      const config = job.config || applyBranding(generateConfig(job.answers as IntakeAnswers), job.branding)
      const A2 = job.answers as IntakeAnswers
      const isGame = A2?.archetype === "game" ||
        looksLikeGame(`${config.identity.name} ${A2?.what || ""} ${typeof config.identity.tagline === "string" ? config.identity.tagline : ""}`)

      // GAME MOLD: a game is not tables→routes→pages — route to the dedicated builder.
      if (isGame) {
        const gs = job.artifacts.gameState || initGameState()
        const gr = await gameAdvance(config, job.artifacts.reference || A2?.references || "", gs)
        job.artifacts.gameState = gr.state
        step.detail = "🎮 " + gr.detail
        if (gr.done) {
          job.artifacts.appFiles = gr.state.files
          const hasScores = gr.state.files.some((f) => /app\.sql$/.test(f.path))
          job.artifacts.blueprint = {
            kind: "public", summary: gr.state.design?.pitch || "",
            tables: hasScores ? [{ name: "scores", ddl: "" }] : [],
            routes: gr.state.files.filter((f) => /route\.ts$/.test(f.path)).map((f) => ({ path: f.path, methods: ["GET", "POST"], purpose: "leaderboard", logic: "" })),
            pages: [{ route: "/", file: "app/page.tsx", title: gr.state.design?.title || config.identity.name, behavior: "the playable game" }],
            nav: [],
          }
          const main = gr.state.files.find((f) => f.path === "app/page.tsx")
          if (main) job.artifacts.engine = { path: main.path, code: main.content }
          step.status = "done"
          step.detail = `🎮 ${gr.state.files.length} archivos · ${gr.state.design?.genre || "juego"}${hasScores ? " · leaderboard" : ""}`
        }
        await persist(job, true)
        return job
      }

      // iteration 3: if a genetic-tournament winning blueprint was injected, build THAT
      // (skip planning) so the winning team's design becomes the real app.
      const state = job.artifacts.engineState || (job.artifacts.winnerBlueprint ? initEngineStateWith(job.artifacts.winnerBlueprint) : initEngineState())
      const r = await buildAdvance(config, job.artifacts.contracts || "", job.artifacts.research || "", job.artifacts.reference || "", state)
      job.artifacts.engineState = r.state
      step.detail = r.detail
      if (r.done) {
        job.artifacts.appFiles = r.state.files
        job.artifacts.blueprint = r.state.blueprint
        const main = r.state.files.find((f) => /route\.ts$/.test(f.path)) || r.state.files[0]
        if (main) job.artifacts.engine = { path: main.path, code: main.content }
        step.status = "done"
        step.detail = `${r.state.files.length} archivos · ${r.state.blueprint?.tables.length || 0} tablas · ${r.state.files.filter((f) => /route\.ts$/.test(f.path)).length} rutas · ${r.state.files.filter((f) => /page\.tsx$/.test(f.path)).length} páginas`
      }
    } catch (e) { step.detail = "engine (reintenta): " + (e as Error).message.slice(0, 80) } // stays running → next call resumes
    await persist(job, true)
    return job
  }

  // stakeholder is RE-ENTRANT for the same reason: the governance layer (3 supervisions ×
  // 5 specialists + the queen's fixers) is multi-minute, so we advance ONE bounded wave
  // (one review batch OR one fix batch) per call and resume from persisted state. This is
  // what makes the 3-iteration review actually COMPLETE on serverless instead of timing out.
  if (step.key === "stakeholder") {
    step.status = "running"; step.startedAt = new Date().toISOString(); job.artifacts = job.artifacts || {}
    try {
      if (job.config && job.artifacts.appFiles && job.artifacts.blueprint) {
        const state = job.artifacts.stakeholderState || initStakeholderState(3)
        const r = await stakeholderAdvance(job.artifacts.appFiles, job.config, job.artifacts.blueprint, state)
        job.artifacts.appFiles = r.files
        job.artifacts.stakeholderState = r.state
        step.detail = r.detail
        if (r.done) {
          const fixed = r.state.reports.reduce((n, rr) => n + rr.filesFixed.length, 0)
          job.artifacts.stakeholderReport = { rounds: r.state.reports, passed: r.state.passed }
          step.detail = `${r.state.reports.length} supervisiones · ${fixed} archivos mejorados${r.state.passed ? " · aprobado" : ""}`
          step.status = "done"
        }
      } else { step.detail = "—"; step.status = "done" }
    } catch (e) { step.detail = "stakeholder (reintenta): " + (e as Error).message.slice(0, 80) } // stays running → next call resumes
    await persist(job, true)
    return job
  }

  step.status = "running"; step.startedAt = new Date().toISOString(); step.attempts = (step.attempts || 0) + 1
  await persist(job)
  try {
    const A = job.answers as IntakeAnswers
    job.artifacts = job.artifacts || {}
    switch (step.key) {
      case "data-model": {
        const config = applyBranding(generateConfig(A), job.branding)
        const ents = await designEntities({ name: A.name, what: A.what, benefits: A.benefits })
        if (ents?.length) config.entities = ents
        job.config = config
        step.detail = (config.entities || []).map((e) => e.name).join(", ")
        break
      }
      case "brand": {
        if (job.config && !job.config.identity.logoSvg && !job.config.identity.logoImage) {
          // art-director first: a REAL logo image if an image provider is configured…
          const img = await generateBrandLogo(job.config).catch(() => null)
          if (img) job.config.identity.logoImage = img.dataUri
          else { const svg = await generateLogoSvg(job.config); if (svg) job.config.identity.logoSvg = svg } // …else the SVG monogram
        }
        step.detail = `Color ${job.config?.identity.brandColor}` + (job.config?.identity.logoImage ? " · logo imagen 🎨" : job.config?.identity.logoSvg ? " · logo SVG" : "")
        break
      }
      case "design": {
        const chosen = job.artifacts.chosenLanding
        job.artifacts.landingHtml = (typeof chosen === "string" && chosen.length > 100) ? chosen : (job.config ? await generateLandingHtml(job.config) : null)
        step.detail = job.artifacts.landingHtml ? `${Math.round(job.artifacts.landingHtml.length / 1024)} KB` : "—"
        break
      }
      case "schema": {
        job.artifacts.sql = genSql(job.config?.entities || [])
        step.detail = `${(job.config?.entities || []).length} tablas`
        break
      }
      case "erd": {
        job.artifacts.erd = genErd(job.config?.entities || [])
        step.detail = "diagrama ER (Mermaid)"
        break
      }
      case "seed": { job.artifacts.seedSql = genSeed(job.config?.entities || []); step.detail = "INSERTs de ejemplo"; break }
      case "auth": step.detail = "JWT (web+móvil), magic-link, verificación, reset — del spine"; break
      case "payments": step.detail = "Stripe subs + webhooks + getEffectivePlan gating — scaffold listo para tus keys"; break
      case "email": step.detail = "Resend + email-logger + bounce poller — del spine"; break
      case "crons": step.detail = "app/api/cron/* fire-and-forget + CRON_SECRET — scaffold"; break
      case "admin": step.detail = "Panel admin gateado — scaffold"; break
      case "dashboard": step.detail = "Dashboard /app con CRUD de tus entidades — del spine"; break
      case "analytics": step.detail = "page_visits + analytics_events + /api/track + A/B — del spine"; break
      case "seo": step.detail = "metadata + sitemap + JSON-LD — scaffold"; break
      case "security": step.detail = "RLS, rate-limit map, security headers, validación — del spine"; break
      case "research": {
        // Researcher: find the REAL external data source(s) for data-driven products, so the
        // seed/catalog mirrors the provider's schema and a cron can pull live data later.
        if (job.config) {
          const [r, ref] = await Promise.all([researchProduct(job.config), studyReference(job.config)])
          job.artifacts.research = r.dataDriven ? r.plan : ""
          // Fold the founder's up-front references (URLs/docs/images digest) into the reference
          // brief so the blueprint reaches their fidelity bar and interprets their data.
          const userRefs = (A.references || "").trim()
          job.artifacts.reference = [ref, userRefs ? `FOUNDER-PROVIDED REFERENCES (match these cues — brand, data, features):\n${userRefs}` : ""].filter(Boolean).join("\n\n")
          const bits = [r.dataDriven ? "fuente de datos real + plan de ingesta" : "sin datos externos", ref ? "producto de referencia mapeado" : "", userRefs ? "referencias del fundador integradas" : ""].filter(Boolean)
          step.detail = bits.join(" · ")
        } else { step.detail = "—" }
        break
      }
      case "contracts": {
        if (job.config) job.artifacts.contracts = await runContracts(job.config)
        step.detail = job.artifacts.contracts ? "tipos + contrato de API definidos" : "—"
        break
      }
      // "engine" and "stakeholder" are handled re-entrantly BEFORE the switch (resumable
      // buildAdvance / stakeholderAdvance) — never here.
      case "docs-tech": {
        if (job.config) job.artifacts.techDocs = await genTechnicalDocs(job.config, job.artifacts.contracts || "", job.artifacts.erd || "")
        step.detail = `${(job.artifacts.techDocs || []).length} docs técnicos`
        break
      }
      case "docs-biz": {
        if (job.config) job.artifacts.bizDocs = await genBusinessDocs(job.config)
        const n = (job.artifacts.bizDocs || []).length
        const deck = (job.artifacts.bizDocs || []).some((f: any) => f.path.endsWith(".html"))
        step.detail = `${n} docs de negocio${deck ? " + pitch deck" : ""}`
        break
      }
      case "env": { job.artifacts.envFile = genEnvExample(job.artifacts.creds); step.detail = "(.env.example + analytics cableado)"; break }
      case "deliver": {
        if (job.config) {
          await saveProject({ slug: job.slug, email: job.email, name: job.name, answers: A as any, config: job.config, landingHtml: job.artifacts.landingHtml })
          if (githubConfigured()) {
            const bp = job.artifacts.blueprint
            const report = `# Build report — ${job.name}\n\n## Bespoke app (generation swarm)\n\n${bp?.summary || ""}\n\n- Tablas: ${(bp?.tables || []).map((t: any) => t.name).join(", ") || "—"}\n- Rutas API: ${(bp?.routes || []).map((r: any) => r.path).join(", ") || "—"}\n- Pantallas: ${(bp?.pages || []).map((p: any) => p.route).join(", ") || "—"}\n`
            const extraFiles = [
              { path: ".env.example", content: job.artifacts.envFile || genEnvExample(job.artifacts.creds) },
              { path: "sql/schema.sql", content: job.artifacts.sql || "" },
              { path: "sql/seed.sql", content: job.artifacts.seedSql || "" },
              { path: "docs/ER-DIAGRAM.md", content: "```mermaid\n" + (job.artifacts.erd || "") + "\n```" },
              { path: "docs/CONTRACTS.md", content: job.artifacts.contracts || "" },
              { path: "docs/BUILD_REPORT.md", content: report },
              ...((job.artifacts.appFiles || []) as { path: string; content: string }[]),
              ...((job.artifacts.techDocs || []) as { path: string; content: string }[]),
              ...((job.artifacts.bizDocs || []) as { path: string; content: string }[]),
              ...harnessFiles(job.name), // self-contained run-&-test harness (docker, db-setup, e2e, README)
            ].filter((f) => f.content)
            const readme = `# ${job.name}\n\nGenerated by [Puglit](https://puglit.com) — open-source SaaS factory.\n\n## Probar end-to-end\nVer **RUN-AND-TEST.md** (docker compose → db-setup → npm run dev → scripts/e2e.mjs).\n\n- \`app/\` — Next.js 16 app (auth, dashboard, bespoke screens)\n- \`sql/\` — migrations (001/002/003 spine + app.sql bespoke)\n- \`docs/\` — architecture, ER diagram, contracts, business docs\n- \`scripts/e2e.mjs\` — end-to-end smoke test of the real user flow\n`
            const built = await assembleProject({ slug: job.slug, name: job.name, configTs: configToTs(job.config), readme, extraFiles })
            job.artifacts.githubUrl = built.url
          }
          job.artifacts.previewUrl = `/x/${job.slug}`
        }
        break
      }
    }
    step.status = "done"; step.finishedAt = new Date().toISOString()
    if (!job.steps.some((s) => s.status === "pending")) {
      job.status = "done"
      await sendDoneEmail(job)
    }
  } catch (e) {
    const msg = (e as Error).message.slice(0, 140)
    if ((step.attempts || 0) < MAX_ATTEMPTS) { step.status = "pending"; step.detail = `reintento ${step.attempts}/${MAX_ATTEMPTS}: ${msg}` }
    else { step.status = "error"; step.detail = msg; job.status = "error"; job.error = `${step.key}: ${msg}` }
  }
  await persist(job, true) // release the lease
  return job
}

/** Watchdog: promote queued, recover stuck steps, and continue running jobs even
 *  if nobody has the build page open. Meant to be hit by a cron every minute. */
export async function sweep(): Promise<{ promoted: boolean; advanced: string[]; recovered: number }> {
  await promoteQueued()
  let recovered = 0
  // recover stuck "running" steps (lease expired + step started too long ago)
  const stuck = await query(
    `SELECT id, steps FROM puglit_jobs WHERE status='running' AND (lease_until IS NULL OR lease_until < NOW())`)
  for (const row of stuck.rows) {
    const steps: Step[] = row.steps
    let changed = false
    for (const s of steps) {
      // ci-verify/engine/stakeholder are re-entrant and run multi-minute waves — give them a far longer leash.
      const timeout = (s.key === "ci-verify" || s.key === "engine" || s.key === "stakeholder") ? CI_STEP_TIMEOUT_MS : STEP_TIMEOUT_MS
      if (s.status === "running" && s.startedAt && Date.now() - new Date(s.startedAt).getTime() > timeout) {
        if ((s.attempts || 0) < MAX_ATTEMPTS) { s.status = "pending"; s.detail = "recuperado (estaba trabado)" }
        else { s.status = "error" }
        changed = true; recovered++
      }
    }
    if (changed) await query(`UPDATE puglit_jobs SET steps=$2, updated_at=NOW() WHERE id=$1`, [row.id, JSON.stringify(steps)])
  }
  // advance each running job by one step (drives jobs forward headlessly)
  const running = await query(`SELECT id FROM puglit_jobs WHERE status='running' ORDER BY updated_at ASC LIMIT $1`, [CONCURRENCY])
  const ids = running.rows.map((r) => r.id)
  // advance jobs in parallel — independent, each guarded by its own lease
  await Promise.all(ids.map((id) => advanceJob(id).catch(() => {})))
  return { promoted: true, advanced: ids, recovered }
}

// Re-entrant CI verify+repair: one short action per call (dispatch / poll / fix).
async function handleCiVerify(job: JobRow, step: Step): Promise<void> {
  const ci = (job.artifacts.ci ||= { attempt: 0, runId: null, waitingSince: null })
  if (!githubConfigured()) { step.status = "done"; step.detail = "sin GITHUB_TOKEN — CI omitido"; return }
  if (step.status === "pending") {
    step.status = "running"; step.startedAt = new Date().toISOString()
    await dispatchCi(job.slug); ci.runId = null; ci.waitingSince = new Date().toISOString()
    step.detail = "compilando en CI…"; return
  }
  if (!ci.runId) {
    const r = await latestRun()
    if (r && (!ci.waitingSince || new Date(r.created_at).getTime() >= new Date(ci.waitingSince).getTime() - 8000)) ci.runId = r.id
    // Self-heal: if we've waited too long with no matching run, the dispatch never
    // landed (or the job predates this fix) — re-dispatch instead of waiting forever.
    if (!ci.runId && ci.waitingSince && Date.now() - new Date(ci.waitingSince).getTime() > 120_000) {
      if ((ci.redispatches ||= 0) < 2) { ci.redispatches++; await dispatchCi(job.slug); ci.waitingSince = new Date().toISOString(); step.detail = "re-disparando CI (espera vencida)"; return }
      step.status = "done"; step.detail = "CI no arrancó tras reintentos"; job.artifacts.ciGreen = false; return
    }
    step.detail = ci.runId ? "CI en cola…" : "esperando CI…"; return
  }
  const run = await getRun(ci.runId)
  if (!run) { step.detail = "CI: run no encontrado"; return }
  if (run.status !== "completed") { step.detail = `CI compilando (${run.status})`; return }
  if (run.conclusion === "success") { step.status = "done"; step.detail = `✅ compila (intentos: ${ci.attempt})`; job.artifacts.ciGreen = true; return }
  if (ci.attempt >= MAX_CI) { step.status = "done"; step.detail = `verde no alcanzado en ${MAX_CI} intentos`; job.artifacts.ciGreen = false; return }
  const errors: CiError[] = await runErrors(ci.runId, job.slug)
  job.artifacts.ciErrors = errors.slice(0, 20)
  if (!errors.length) { step.status = "done"; step.detail = "CI falló sin errores legibles en logs"; job.artifacts.ciGreen = false; return }
  const { fixed } = await fixFiles(errors) // pushes fixes → push triggers a fresh CI run
  if (!fixed.length) { step.status = "done"; step.detail = `${errors.length} errores tsc no reparables automáticamente — entregado con reporte`; job.artifacts.ciGreen = false; return }
  ci.attempt++; ci.runId = null; ci.waitingSince = new Date().toISOString()
  step.detail = `reparando (intento ${ci.attempt}/${MAX_CI}): ${fixed.length}/${errors.length} archivos`
}

function configToTs(config: DomainConfig): string {
  return `export * from "./domain-types"\nimport type { DomainConfig } from "./domain-types"\nconst config: DomainConfig = ${JSON.stringify(config, null, 2)}\nexport default config\n`
}

async function sendDoneEmail(job: JobRow) {
  const key = process.env.RESEND_API_KEY
  if (!key || !job.email) return
  const base = process.env.APP_URL || "https://puglit-home.vercel.app"
  try {
    await fetch("https://api.resend.com/emails", {
      method: "POST", headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        from: process.env.WAITLIST_FROM || "Puglit <onboarding@resend.dev>", to: job.email,
        subject: `🐶 ${job.name} está listo`,
        html: `<p>Tu proyecto <b>${job.name}</b> está listo.</p><p><a href="${base}/build/${job.id}">Ver el build</a> · <a href="${base}${job.artifacts?.previewUrl || ""}">Preview</a>${job.artifacts?.githubUrl ? ` · <a href="${job.artifacts.githubUrl}">Código</a>` : ""}</p>`,
      }),
    })
  } catch { /* email optional */ }
}
