import { NextRequest, NextResponse } from "next/server"
import { getAuthUser } from "@/lib/auth"
import { pool } from "@/lib/db"

// Deterministic membership toggle (generated by Puglit): own/disown a program by id.
export async function POST(request: NextRequest) {
  const u = await getAuthUser(request)
  if (!u) return NextResponse.json({ error: "unauthorized" }, { status: 401 })
  const b = await request.json().catch(() => ({}))
  const programId = Number(b.program_id ?? b.programId ?? b.id)
  if (!programId) return NextResponse.json({ error: "program_id required" }, { status: 400 })
  await pool.query("INSERT INTO user_memberships (user_id, program_id) SELECT $1, $2 WHERE NOT EXISTS (SELECT 1 FROM user_memberships WHERE user_id=$1 AND program_id=$2)", [u.userId, programId])
  return NextResponse.json({ ok: true })
}

export async function DELETE(request: NextRequest) {
  const u = await getAuthUser(request)
  if (!u) return NextResponse.json({ error: "unauthorized" }, { status: 401 })
  const b = await request.json().catch(() => ({}))
  const programId = Number(b.program_id ?? b.programId ?? b.id)
  await pool.query("DELETE FROM user_memberships WHERE user_id=$1 AND program_id=$2", [u.userId, programId])
  return NextResponse.json({ ok: true })
}

export async function GET(request: NextRequest) {
  const u = await getAuthUser(request)
  if (!u) return NextResponse.json({ error: "unauthorized" }, { status: 401 })
  const { rows } = await pool.query("SELECT m.program_id, to_json(p) AS program FROM user_memberships m JOIN loyalty_programs p ON p.id = m.program_id WHERE m.user_id = $1", [u.userId])
  return NextResponse.json(rows)
}
