export * from "./domain-types"
import type { DomainConfig } from "./domain-types"

// Generated by Puglit (https://puglit.com). Edit this file — the whole app follows.
const config: DomainConfig = {
  "infra": {
    "deploy": "fly",
    "emailProvider": "resend"
  },
  "landing": {
    "faq": [
      {
        "a": "alarma online is free.",
        "q": "How much does it cost?"
      },
      {
        "a": "Yes — one click, no questions.",
        "q": "Can I cancel anytime?"
      },
      {
        "a": "Yes. Your data is yours and you can export it.",
        "q": "Do I own my data?"
      }
    ],
    "hero": {
      "headline": "alarma que suena incluso cuando el navegador está cerrado",
      "ctaPrimary": "Get started",
      "subheadline": "alarma online",
      "ctaSecondary": "See pricing"
    },
    "finalCta": {
      "button": "Get started",
      "headline": "Ready to try alarma online?"
    },
    "valueProps": [
      {
        "body": "Built into alarma online from day one — no glue code.",
        "title": "alarma que suena incluso cuando el navegador está cerrado"
      },
      {
        "body": "It just works, so you can focus on your users.",
        "title": "sugerencias de tiempos de estudio y descanso basadas en el método Pomodoro"
      },
      {
        "body": "Reliable, secure and ready to scale.",
        "title": "registro del tema de estudio y progreso con emoticonos"
      }
    ],
    "socialProof": "Made for estudiantes."
  },
  "modules": {
    "engine": true,
    "gamification": true
  },
  "entities": [
    {
      "name": "Alarm",
      "fields": [
        {
          "name": "time",
          "type": "datetime",
          "required": true
        },
        {
          "name": "label",
          "type": "text",
          "required": true
        },
        {
          "name": "is_active",
          "type": "bool",
          "required": true
        }
      ],
      "plural": "Alarms",
      "ownedByUser": true
    },
    {
      "name": "StudySession",
      "fields": [
        {
          "name": "subject",
          "type": "text",
          "required": true
        },
        {
          "name": "duration",
          "type": "int",
          "required": true
        },
        {
          "name": "emoticon",
          "type": "text",
          "required": false
        },
        {
          "name": "date",
          "type": "date",
          "required": true
        }
      ],
      "plural": "StudySessions",
      "ownedByUser": true
    },
    {
      "name": "PomodoroSuggestion",
      "fields": [
        {
          "name": "study_time",
          "type": "int",
          "required": true
        },
        {
          "name": "break_time",
          "type": "int",
          "required": true
        },
        {
          "name": "suggestion_date",
          "type": "date",
          "required": true
        }
      ],
      "plural": "PomodoroSuggestions",
      "ownedByUser": true
    }
  ],
  "identity": {
    "name": "alarma online",
    "domain": "alarma-online.app",
    "palette": [
      {
        "hex": "#4A90E2",
        "label": "Azul calmante"
      },
      {
        "hex": "#7ED321",
        "label": "Verde fresco"
      },
      {
        "hex": "#F8E71C",
        "label": "Amarillo energético"
      },
      {
        "hex": "#F5A623",
        "label": "Naranja estimulante"
      },
      {
        "hex": "#FFFFFF",
        "label": "Fondo blanco"
      },
      {
        "hex": "#000000",
        "label": "Texto negro"
      }
    ],
    "tagline": "alarma online",
    "languages": [
      "en",
      "es"
    ],
    "brandColor": "#4A90E2",
    "accentColor": "#F8E71C",
    "logoConcept": "Un reloj estilizado con las letras 'AO' en el centro, simbolizando la gestión del tiempo.",
    "logoMonogram": "AO",
    "targetMarkets": [],
    "secondaryColor": "#7ED321"
  },
  "platforms": {
    "web": true,
    "admin": true
  },
  "monetization": {
    "model": "free",
    "plans": [
      {
        "id": "free",
        "features": [
          "Core features",
          "Community support"
        ],
        "priceUsd": 0
      }
    ],
    "providers": [
      "stripe"
    ]
  }
}

export default config
