#!/usr/bin/env bash
# BYO (bring-your-own) deploy of a built Puglit app to the USER's OWN accounts.
# Tokens come from env and are NEVER stored. Puglit pays nothing — you own the deploy.
#
#   GH_TOKEN=ghp_xxx [VERCEL_TOKEN=yyy] bash infra/deploy.sh <PROJECT_DIR> [repo-name]
#
# GitHub = UNIVERSAL output: works for ANY app type (web, mobile, CLI…) → your code in your
#          repo. Always run this.
# Vercel = OPTIONAL, web apps only: also gives a live public URL. Skipped if it's not a web app
#          or you don't pass VERCEL_TOKEN.
set -e
DIR="${1:?uso: deploy.sh <PROJECT_DIR> [repo-name]}"
REPO="${2:-puglit-app}"
cd "$DIR"

if [ -z "$GH_TOKEN" ] && [ -z "$VERCEL_TOKEN" ]; then
  echo "(sin GH_TOKEN ni VERCEL_TOKEN → nada que deployar. Seteá al menos GH_TOKEN.)"
  exit 0
fi

# ── GitHub (universal: any app type) ─────────────────────────────────────────
if [ -n "$GH_TOKEN" ]; then
  GH_USER="$(curl -s -H "Authorization: Bearer $GH_TOKEN" https://api.github.com/user | jq -r '.login // empty')"
  if [ -z "$GH_USER" ]; then echo "✗ GitHub: token inválido"; exit 1; fi
  echo "→ GitHub: $GH_USER/$REPO (creando + push)…"
  curl -s -H "Authorization: Bearer $GH_TOKEN" -H "Accept: application/vnd.github+json" \
    https://api.github.com/user/repos -d "{\"name\":\"$REPO\",\"private\":false,\"description\":\"Generated by Puglit\"}" >/dev/null || true
  printf "node_modules\n.next\n.env.local\n.vercel\n" > .gitignore
  git init -q 2>/dev/null || true
  git add -A
  git -c user.email=puglit@puglit.app -c user.name=Puglit commit -qm "Generated by Puglit" >/dev/null 2>&1 || true
  git branch -M main 2>/dev/null || true
  git remote remove origin 2>/dev/null || true
  git remote add origin "https://${GH_TOKEN}@github.com/${GH_USER}/${REPO}.git"
  if git push -q -u origin main --force; then echo "✓ GitHub: https://github.com/${GH_USER}/${REPO}"; else echo "✗ GitHub push falló"; fi
fi

# ── Vercel (optional: web apps only) ─────────────────────────────────────────
if [ -n "$VERCEL_TOKEN" ]; then
  echo "→ Vercel: deployando (solo apps web)…"
  URL="$(npx --yes vercel@latest --token "$VERCEL_TOKEN" --yes --prod --cwd "$DIR" 2>&1 | grep -Eo 'https://[a-zA-Z0-9./-]+\.vercel\.app' | tail -1)"
  if [ -n "$URL" ]; then echo "✓ Vercel: $URL"; else echo "✗ Vercel: revisá el token (o no es una app web deployable)"; fi
fi
