import { NextRequest, NextResponse } from "next/server"
import { getAuthUser } from "@/lib/auth"
import { pool } from "@/lib/db"

// Deterministic, parameter-safe swipe → mutual-match (generated by Puglit, not the LLM).
export async function POST(request: NextRequest) {
  const u = await getAuthUser(request)
  if (!u) return NextResponse.json({ error: "unauthorized" }, { status: 401 })
  const b = await request.json().catch(() => ({}))
  const itemId = Number(b.item_id ?? b.itemId ?? b.id)
  const liked = b.liked ?? b.like ?? true
  if (!itemId) return NextResponse.json({ error: "item_id required" }, { status: 400 })

  await pool.query("INSERT INTO swipes (user_id, item_id, liked) VALUES ($1,$2,$3)", [u.userId, itemId, liked])

  let matchId: number | null = null
  if (liked) {
    // mutual iff the owner of the item I liked has already liked one of MY items
    const mutual = await pool.query(
      `SELECT s.user_id AS other_user, s.item_id AS other_item
       FROM swipes s
       WHERE s.liked = true
         AND s.item_id IN (SELECT id FROM items WHERE owner_id = $1)
         AND s.user_id = (SELECT owner_id FROM items WHERE id = $2)
       LIMIT 1`,
      [u.userId, itemId]
    )
    if (mutual.rows.length > 0) {
      const r = await pool.query(
        "INSERT INTO matches (user_a, user_b, item_a, item_b) VALUES ($1,$2,$3,$4) RETURNING id",
        [u.userId, mutual.rows[0].other_user, itemId, mutual.rows[0].other_item]
      )
      matchId = r.rows[0].id
    }
  }
  return NextResponse.json({ success: true, matchId })
}
