export * from "./domain-types"
import type { DomainConfig } from "./domain-types"

// Generated by Puglit (https://puglit.com). Edit this file — the whole app follows.
const config: DomainConfig = {
  "infra": {
    "deploy": "fly",
    "emailProvider": "resend"
  },
  "landing": {
    "faq": [
      {
        "a": "Brote is free.",
        "q": "How much does it cost?"
      },
      {
        "a": "Yes — one click, no questions.",
        "q": "Can I cancel anytime?"
      },
      {
        "a": "Yes. Your data is yours and you can export it.",
        "q": "Do I own my data?"
      }
    ],
    "hero": {
      "headline": "Never forget to water",
      "ctaPrimary": "Get started",
      "subheadline": "Reminders and care tips for your houseplants so they never die",
      "ctaSecondary": "See pricing"
    },
    "finalCta": {
      "button": "Get started",
      "headline": "Ready to try Brote?"
    },
    "valueProps": [
      {
        "body": "Built into Brote from day one — no glue code.",
        "title": "Never forget to water"
      },
      {
        "body": "It just works, so you can focus on your users.",
        "title": "Care tips per plant"
      },
      {
        "body": "Reliable, secure and ready to scale.",
        "title": "All my plants in one place"
      }
    ],
    "socialProof": "Made for Plant enthusiasts."
  },
  "modules": {
    "profiling": true
  },
  "entities": [
    {
      "name": "Item",
      "fields": [
        {
          "name": "title",
          "type": "text",
          "required": true
        },
        {
          "name": "data",
          "type": "json"
        }
      ],
      "ownedByUser": true
    }
  ],
  "identity": {
    "name": "Brote",
    "domain": "brote.app",
    "tagline": "Reminders and care tips for your houseplants so they never die",
    "languages": [
      "en"
    ],
    "brandColor": "#4CAF50",
    "targetMarkets": []
  },
  "platforms": {
    "web": true,
    "admin": true
  },
  "monetization": {
    "model": "free",
    "plans": [
      {
        "id": "free",
        "features": [
          "Core features",
          "Community support"
        ],
        "priceUsd": 0
      }
    ],
    "providers": [
      "stripe"
    ]
  }
}

export default config
