-- Promiedos — catalog seed (generated by Puglit's Data Ingestion agent).
-- Real-world reference data so the app works on first run; refresh via app/api/cron/refresh.

-- seed
INSERT INTO tournaments (id, name, start_date, end_date, current_stage) VALUES
  (1, 'Liga Profesional de Fútbol', CURRENT_DATE - INTERVAL '3 months', CURRENT_DATE + INTERVAL '3 months', 'Primera División'),
  (2, 'Copa de la Liga Profesional', CURRENT_DATE - INTERVAL '2 months', CURRENT_DATE + INTERVAL '1 month', 'Fase de Grupos');

INSERT INTO matches (id, date_time, team_home, team_away, score_home, score_away) VALUES
  (1, NOW() - INTERVAL '1 day', 'Boca Juniors', 'River Plate', 1, 1),
  (2, NOW(), 'Racing Club', 'Independiente', NULL, NULL),
  (3, NOW() + INTERVAL '2 hours', 'San Lorenzo', 'Vélez Sarsfield', NULL, NULL),
  (4, NOW() + INTERVAL '1 day', 'Rosario Central', 'Newell''s Old Boys', NULL, NULL),
  (5, NOW() - INTERVAL '3 days', 'Estudiantes', 'Gimnasia', 2, 0),
  (6, NOW() + INTERVAL '3 days', 'Talleres', 'Belgrano', NULL, NULL);

INSERT INTO standings (id, tournament_id, team_name, points, matches_played, goal_difference) VALUES
  (1, 1, 'Boca Juniors', 25, 12, 10),
  (2, 1, 'River Plate', 24, 12, 8),
  (3, 1, 'Racing Club', 22, 12, 5),
  (4, 1, 'Independiente', 20, 12, 3),
  (5, 1, 'San Lorenzo', 18, 12, 2),
  (6, 1, 'Vélez Sarsfield', 15, 12, 0),
  (7, 1, 'Rosario Central', 14, 12, -2),
  (8, 1, 'Newell''s Old Boys', 13, 12, -3),
  (9, 1, 'Estudiantes', 12, 12, -5),
  (10, 1, 'Gimnasia', 10, 12, -7);

INSERT INTO scorers (id, player_name, team_name, goals, tournament_id) VALUES
  (1, 'Carlos Tevez', 'Boca Juniors', 10, 1),
  (2, 'Lucas Pratto', 'River Plate', 9, 1),
  (3, 'Lisandro López', 'Racing Club', 8, 1),
  (4, 'Silvio Romero', 'Independiente', 7, 1),
  (5, 'Ángel Romero', 'San Lorenzo', 6, 1),
  (6, 'Maxi Moralez', 'Vélez Sarsfield', 5, 1);
