export * from "./domain-types"
import type { DomainConfig } from "./domain-types"

// Generated by Puglit (https://puglit.com). Edit this file — the whole app follows.
const config: DomainConfig = {
  "infra": {
    "deploy": "fly",
    "emailProvider": "resend"
  },
  "landing": {
    "faq": [
      {
        "a": "Empezás gratis y después un plan mensual simple. Cancelás cuando quieras.",
        "q": "¿Cuánto cuesta?"
      },
      {
        "a": "Sí — en un clic, sin preguntas.",
        "q": "¿Puedo cancelar cuando quiera?"
      },
      {
        "a": "Sí. Tus datos son tuyos y los podés exportar.",
        "q": "¿Mis datos son míos?"
      }
    ],
    "hero": {
      "headline": "Autorización de tarjeta de crédito",
      "ctaPrimary": "Empezar gratis",
      "subheadline": "Sistema de reservas online para restaurantes que gestiona las mesas y maneja un cobro de tarjeta de crédito.",
      "ctaSecondary": "Ver precios"
    },
    "finalCta": {
      "button": "Empezar gratis",
      "headline": "¿List@ para probar Mesa?"
    },
    "valueProps": [
      {
        "body": "Viene en Mesa desde el día uno — sin código pegamento.",
        "title": "Autorización de tarjeta de crédito"
      },
      {
        "body": "Funciona solo, para que te enfoques en tus usuarios.",
        "title": "Opciones de pago en efectivo o Yape"
      },
      {
        "body": "Confiable, seguro y listo para escalar.",
        "title": "Gestión de disponibilidad de mesas"
      }
    ],
    "socialProof": "Hecho para Restaurantes."
  },
  "modules": {
    "growth": true,
    "payments": true,
    "emailLifecycle": true
  },
  "entities": [
    {
      "name": "Table",
      "fields": [
        {
          "name": "table_number",
          "type": "int",
          "required": true
        },
        {
          "name": "seating_capacity",
          "type": "int",
          "required": true
        },
        {
          "name": "is_available",
          "type": "bool",
          "required": true
        }
      ],
      "plural": "Tables",
      "ownedByUser": true
    },
    {
      "name": "Reservation",
      "fields": [
        {
          "name": "customer_name",
          "type": "text",
          "required": true
        },
        {
          "name": "reservation_date",
          "type": "datetime",
          "required": true
        },
        {
          "name": "table_id",
          "type": "int",
          "required": true
        },
        {
          "name": "payment_method",
          "type": "enum",
          "required": true,
          "enumValues": [
            "credit_card",
            "cash",
            "yape"
          ]
        }
      ],
      "plural": "Reservations",
      "ownedByUser": true
    },
    {
      "name": "Payment",
      "fields": [
        {
          "name": "amount",
          "type": "float",
          "required": true
        },
        {
          "name": "payment_date",
          "type": "datetime",
          "required": true
        },
        {
          "name": "reservation_id",
          "type": "int",
          "required": true
        },
        {
          "name": "is_successful",
          "type": "bool",
          "required": true
        }
      ],
      "plural": "Payments",
      "ownedByUser": true
    }
  ],
  "identity": {
    "name": "Mesa",
    "domain": "mesa.app",
    "tagline": "Sistema de reservas online para restaurantes que gestiona las mesas y maneja un cobro de tarjeta de crédito.",
    "languages": [
      "es"
    ],
    "brandColor": "#4CAF50",
    "targetMarkets": []
  },
  "platforms": {
    "web": true,
    "admin": true
  },
  "monetization": {
    "model": "subscription",
    "plans": [
      {
        "id": "pro",
        "features": [
          "Autorización de tarjeta de crédito",
          "Opciones de pago en efectivo o Yape",
          "Gestión de disponibilidad de mesas",
          "Soporte prioritario"
        ],
        "interval": "month",
        "priceUsd": 9,
        "highlight": true
      },
      {
        "id": "anual",
        "features": [
          "Todo lo de Pro",
          "2 meses gratis"
        ],
        "interval": "year",
        "priceUsd": 90
      }
    ],
    "providers": [
      "stripe"
    ]
  }
}

export default config
