export * from "./domain-types"
import type { DomainConfig } from "./domain-types"

// Generated by Puglit (https://puglit.com). Edit this file — the whole app follows.
const config: DomainConfig = {
  "infra": {
    "deploy": "fly",
    "emailProvider": "resend"
  },
  "landing": {
    "faq": [
      {
        "a": "no fumar es gratis.",
        "q": "¿Cuánto cuesta?"
      },
      {
        "a": "Sí — en un clic, sin preguntas.",
        "q": "¿Puedo cancelar cuando quiera?"
      },
      {
        "a": "Sí. Tus datos son tuyos y los podés exportar.",
        "q": "¿Mis datos son míos?"
      }
    ],
    "hero": {
      "headline": "Seguimiento del consumo de cigarrillos",
      "ctaPrimary": "Empezar gratis",
      "subheadline": "Aplicación para dejar de fumar",
      "ctaSecondary": "Ver precios"
    },
    "finalCta": {
      "button": "Empezar gratis",
      "headline": "¿List@ para probar no fumar?"
    },
    "valueProps": [
      {
        "body": "Viene en no fumar desde el día uno — sin código pegamento.",
        "title": "Seguimiento del consumo de cigarrillos"
      },
      {
        "body": "Funciona solo, para que te enfoques en tus usuarios.",
        "title": "Gráficos sobre días de vida perdidos"
      },
      {
        "body": "Confiable, seguro y listo para escalar.",
        "title": "Cálculo del dinero gastado en tabaco"
      }
    ],
    "socialProof": "Hecho para Fumadores actuales."
  },
  "modules": {
    "profiling": true,
    "gamification": true
  },
  "entities": [
    {
      "name": "CigaretteConsumption",
      "fields": [
        {
          "name": "date",
          "type": "date",
          "required": true
        },
        {
          "name": "cigarettes_smoked",
          "type": "int",
          "required": true
        },
        {
          "name": "money_spent",
          "type": "float",
          "required": true
        }
      ],
      "plural": "CigaretteConsumptions",
      "ownedByUser": true
    },
    {
      "name": "LifeLost",
      "fields": [
        {
          "name": "date",
          "type": "date",
          "required": true
        },
        {
          "name": "days_lost",
          "type": "int",
          "required": true
        }
      ],
      "plural": "LifeLosts",
      "ownedByUser": true
    },
    {
      "name": "UserProfile",
      "fields": [
        {
          "name": "username",
          "type": "text",
          "required": true
        },
        {
          "name": "email",
          "type": "email",
          "required": true
        },
        {
          "name": "quit_date",
          "type": "date",
          "required": false
        }
      ],
      "plural": "UserProfiles",
      "ownedByUser": true
    }
  ],
  "identity": {
    "name": "no fumar",
    "domain": "no-fumar.app",
    "tagline": "Aplicación para dejar de fumar",
    "languages": [
      "es"
    ],
    "brandColor": "#2196F3",
    "targetMarkets": []
  },
  "platforms": {
    "web": true,
    "admin": true
  },
  "monetization": {
    "model": "free",
    "plans": [
      {
        "id": "free",
        "features": [
          "Funciones principales",
          "Soporte de la comunidad"
        ],
        "priceUsd": 0
      }
    ],
    "providers": [
      "stripe"
    ]
  }
}

export default config
