export * from "./domain-types"
import type { DomainConfig } from "./domain-types"

// Generated by Puglit (https://puglit.com). Edit this file — the whole app follows.
const config: DomainConfig = {
  "infra": {
    "deploy": "fly",
    "emailProvider": "resend"
  },
  "landing": {
    "faq": [
      {
        "a": "Cobi is free.",
        "q": "How much does it cost?"
      },
      {
        "a": "Yes — one click, no questions.",
        "q": "Can I cancel anytime?"
      },
      {
        "a": "Yes. Your data is yours and you can export it.",
        "q": "Do I own my data?"
      }
    ],
    "hero": {
      "headline": "Track every expense automatically",
      "ctaPrimary": "Get started",
      "subheadline": "A simple app to split shared household expenses with roommates.",
      "ctaSecondary": "See pricing"
    },
    "finalCta": {
      "button": "Get started",
      "headline": "Ready to try Cobi?"
    },
    "valueProps": [
      {
        "body": "Built into Cobi from day one — no glue code.",
        "title": "Track every expense automatically"
      },
      {
        "body": "It just works, so you can focus on your users.",
        "title": "Split bills with roommates"
      },
      {
        "body": "Reliable, secure and ready to scale.",
        "title": "See where my money goes"
      }
    ],
    "socialProof": "Made for Roommates."
  },
  "modules": {
    "payments": true
  },
  "entities": [
    {
      "name": "Expense",
      "fields": [
        {
          "name": "description",
          "type": "text",
          "required": true
        },
        {
          "name": "amount",
          "type": "float",
          "required": true
        },
        {
          "name": "date_incurred",
          "type": "date",
          "required": true
        },
        {
          "name": "paid_by",
          "type": "json",
          "required": true
        }
      ],
      "plural": "Expenses",
      "ownedByUser": true
    },
    {
      "name": "Roommate",
      "fields": [
        {
          "name": "name",
          "type": "text",
          "required": true
        },
        {
          "name": "email",
          "type": "email",
          "required": true
        },
        {
          "name": "share_percentage",
          "type": "float",
          "required": true
        }
      ],
      "plural": "Roommates",
      "ownedByUser": true
    },
    {
      "name": "Bill",
      "fields": [
        {
          "name": "title",
          "type": "text",
          "required": true
        },
        {
          "name": "total_amount",
          "type": "float",
          "required": true
        },
        {
          "name": "due_date",
          "type": "date",
          "required": true
        },
        {
          "name": "status",
          "type": "enum",
          "required": true,
          "enumValues": [
            "paid",
            "unpaid",
            "overdue"
          ]
        }
      ],
      "plural": "Bills",
      "ownedByUser": true
    }
  ],
  "identity": {
    "name": "Cobi",
    "domain": "cobi.app",
    "tagline": "A simple app to split shared household expenses with roommates.",
    "languages": [
      "en"
    ],
    "brandColor": "#4CAF50",
    "targetMarkets": []
  },
  "platforms": {
    "web": true,
    "admin": true
  },
  "monetization": {
    "model": "free",
    "plans": [
      {
        "id": "free",
        "features": [
          "Core features",
          "Community support"
        ],
        "priceUsd": 0
      }
    ],
    "providers": [
      "stripe"
    ]
  }
}

export default config
