/**
 * EXAMPLE — a sports betting predictions SaaS generated by Puglit.
 * Showcases: ENGINE slot (external model service) + subscription + COMPLIANCE
 * (responsible gambling, age gate) as a first-class concern.
 */
import type { DomainConfig } from "../domain.config"

const betting: DomainConfig = {
  identity: {
    name: "EdgeCast",
    tagline: "Model-driven picks, not hunches",
    domain: "example-betting.com",
    languages: ["en", "es"],
    brandColor: "#16A34A",
    targetMarkets: ["US", "BR", "MX"],
  },

  modules: {
    payments: true,
    emailLifecycle: true,
    aiLayer: true,
    engine: true,        // ← the prediction engine
    profiling: true,
    growth: true,
    gamification: true,  // streaks of following picks
  },

  entities: [
    {
      name: "Match",
      public: true,
      searchable: true,
      fields: [
        { name: "league", type: "text", required: true },
        { name: "home", type: "text", required: true },
        { name: "away", type: "text", required: true },
        { name: "startsAt", type: "datetime", required: true },
        { name: "status", type: "enum", enumValues: ["scheduled", "live", "final"] },
      ],
    },
    {
      name: "Prediction",
      public: false,
      fields: [
        { name: "matchId", type: "ref", ref: "Match", required: true },
        { name: "pick", type: "text", note: "model output: 1X2 / spread / o-u" },
        { name: "edgePct", type: "float", note: "model edge vs market odds" },
        { name: "confidence", type: "float" },
        { name: "rationale", type: "longtext", aiGenerated: true, note: "AI explains the model output in plain language" },
      ],
    },
    {
      name: "FollowedPick",
      ownedByUser: true,
      fields: [{ name: "predictionId", type: "ref", ref: "Prediction", required: true }],
    },
  ],

  engine: {
    kind: "external-service",
    description: "Statistical model that ingests historical results + live market odds and outputs value picks with an edge%.",
    inputs: ["league", "match", "current market odds"],
    output: "pick + edge% + confidence",
    externalServiceEnv: "MODEL_SERVICE_URL", // called via services-config with API key + fallback
  },

  monetization: {
    model: "subscription",
    providers: ["stripe"],
    plans: [
      { id: "free", priceUsd: 0, features: ["1 liga", "picks con 24h de retraso"] },
      { id: "pro", priceUsd: 29, interval: "month", features: ["todas las ligas", "picks en tiempo real", "edge% y rationale"] },
      { id: "annual", priceUsd: 249, interval: "year", features: ["todo Pro", "2 meses gratis"] },
    ],
  },

  compliance: {
    ageGate: 18,
    notices: [
      "Solo para mayores de 18. El juego puede causar adicción — jugá responsablemente.",
      "Las predicciones no garantizan resultados. Apostá solo lo que puedas permitirte perder.",
      "Verificá la legalidad de las apuestas en tu jurisdicción.",
    ],
  },

  platforms: { web: true, mobile: false, admin: true },
  infra: { deploy: "fly", region: "iad", emailProvider: "resend" },
}

export default betting
