/**
 * EXAMPLE — "Pulso", an adaptive AI fitness-coach SaaS generated by Puglit.
 * Founder: ex-personal-trainer. Freemium, Spanish-first (LATAM) + English,
 * mobile-heavy. Showcases: AI engine that adapts a weekly plan from logged
 * performance + feedback, profiling, gamification (streaks), mobile (RevenueCat),
 * and a health-disclaimer compliance block.
 */
import type { DomainConfig } from "../domain.config"

const pulso: DomainConfig = {
  identity: {
    name: "Pulso",
    tagline: { es: "Tu entrenador con IA que se adapta a vos", en: "Your AI coach that adapts to you" },
    domain: "pulso.fit",
    languages: ["es", "en"],
    brandColor: "#F97316", // energetic orange — recolors the entire app
    targetMarkets: ["MX", "AR", "CO", "PE", "CL", "ES", "US"],
  },

  // WHY these modules:
  //  - engine + aiLayer: the product IS an AI plan generator; aiLayer gives the
  //    provider adapter, prompt-service, context-builder (per-user history) and
  //    the guardian (refuse unsafe load given injuries) + cost log.
  //  - payments: freemium gate (free plan = manual, paid = adaptive + unlimited).
  //  - profiling: implicit signals (RPE, completion, skips) feed the next plan.
  //  - gamification: streaks/check-ins are the retention spine of any fitness app.
  //  - mobile: workouts happen at the gym → phone is the primary surface; RevenueCat IAP.
  //  - emailLifecycle: onboarding drip + weekly summary + reengagement on a lapsed streak.
  //  NOT chosen: contentBlog (no editorial ambition at launch), geo (no location features),
  //  growth A/B suite (deferred until there's traffic to test).
  modules: {
    engine: true,
    aiLayer: true,
    payments: true,
    profiling: true,
    gamification: true,
    mobile: true,
    emailLifecycle: true,
  },

  entities: [
    {
      name: "WorkoutPlan",
      plural: "WorkoutPlans",
      ownedByUser: true,
      fields: [
        { name: "week_of", type: "date", required: true, note: "Monday of the plan week" },
        { name: "goal", type: "enum", enumValues: ["perder_grasa", "ganar_musculo", "fuerza", "resistencia", "salud_general"], required: true },
        { name: "equipment", type: "json", note: "array of available equipment tags, e.g. ['mancuernas','banco','sin_equipo']" },
        { name: "days_per_week", type: "int", required: true },
        { name: "session_minutes", type: "int", note: "target minutes per session" },
        { name: "plan", type: "json", aiGenerated: true, required: true, note: "ordered days × blocks × exercises with sets/reps/rest/target-RPE" },
        { name: "status", type: "enum", enumValues: ["activo", "completado", "archivado"], note: "current plan lifecycle" },
        { name: "adapted_from", type: "ref", ref: "WorkoutPlan", note: "previous week this plan adapted from, if any" },
      ],
    },
    {
      name: "Exercise",
      plural: "Exercises",
      public: true,
      searchable: true,
      fields: [
        { name: "name", type: "text", required: true },
        { name: "slug", type: "slug", unique: true },
        { name: "muscle_group", type: "enum", enumValues: ["pecho", "espalda", "piernas", "hombros", "brazos", "core", "full_body"] },
        { name: "equipment", type: "enum", enumValues: ["sin_equipo", "mancuernas", "barra", "maquina", "banda", "kettlebell"] },
        { name: "difficulty", type: "enum", enumValues: ["principiante", "intermedio", "avanzado"] },
        { name: "instructions", type: "longtext", aiGenerated: true, note: "form cues + common-mistake warnings, written safe-first" },
        { name: "videoUrl", type: "url" },
        { name: "contraindications", type: "json", note: "array of injury tags this exercise should be avoided/regressed for" },
      ],
    },
    {
      name: "ProgressLog",
      plural: "ProgressLogs",
      ownedByUser: true,
      searchable: false,
      fields: [
        { name: "planId", type: "ref", ref: "WorkoutPlan", required: true },
        { name: "exerciseId", type: "ref", ref: "Exercise", required: true },
        { name: "logged_at", type: "datetime", required: true },
        { name: "sets_completed", type: "int" },
        { name: "reps", type: "json", note: "array of reps achieved per set" },
        { name: "weight_kg", type: "float" },
        { name: "rpe", type: "int", note: "rate of perceived exertion 1-10, the key adaptation signal" },
        { name: "felt", type: "enum", enumValues: ["facil", "justo", "dificil", "dolor"], note: "subjective feedback; 'dolor' triggers guardian regression" },
        { name: "notes", type: "text" },
      ],
    },
    {
      name: "AthleteProfile",
      plural: "AthleteProfiles",
      ownedByUser: true,
      fields: [
        { name: "experience", type: "enum", enumValues: ["principiante", "intermedio", "avanzado"] },
        { name: "injuries", type: "json", note: "array of injury/limitation tags fed to the guardian, e.g. ['rodilla','lumbar']" },
        { name: "available_days", type: "json", note: "array of weekday availability" },
        { name: "preferences", type: "json", aiGenerated: true, note: "latent profile learned from logs: liked/avoided movements, recovery rate" },
      ],
    },
  ],

  engine: {
    kind: "ai",
    description:
      "Generates and re-generates an adaptive weekly workout plan. Reads the athlete's goal, available equipment, schedule and injuries, then each week adjusts volume/intensity/exercise selection from the prior week's logged performance (completion, RPE, 'felt' feedback). It progresses when sessions feel easy and deloads or regresses movements when RPE is high or pain is reported.",
    inputs: [
      "goal",
      "available equipment",
      "days per week and session length",
      "experience level",
      "injuries / limitations",
      "last week's ProgressLog (sets, reps, weight, RPE, felt)",
    ],
    output: "a structured weekly plan (days × exercises with sets/reps/rest/target-RPE) plus a short rationale of what changed vs last week and why",
  },

  monetization: {
    model: "freemium",
    providers: ["stripe", "revenuecat"], // Stripe on web, RevenueCat for App Store / Play Store IAP
    plans: [
      {
        id: "free",
        name: { es: "Gratis", en: "Free" },
        priceUsd: 0,
        features: [
          { es: "1 plan semanal generado por IA", en: "1 AI-generated weekly plan" },
          { es: "Biblioteca de ejercicios con técnica", en: "Exercise library with form cues" },
          { es: "Registro de entrenamientos", en: "Workout logging" },
        ],
      },
      {
        id: "pro",
        name: { es: "Pro", en: "Pro" },
        priceUsd: 8,
        interval: "month",
        highlight: true,
        features: [
          { es: "Planes ilimitados que se adaptan cada semana", en: "Unlimited plans that adapt every week" },
          { es: "Ajuste por lesiones y dolor en tiempo real", en: "Real-time injury & pain-aware adjustments" },
          { es: "Progresión automática según tu rendimiento", en: "Automatic progression from your performance" },
          { es: "Rachas, recordatorios y resumen semanal", en: "Streaks, reminders and weekly summary" },
          { es: "Soporte prioritario", en: "Priority support" },
        ],
      },
      {
        id: "anual",
        name: { es: "Pro anual", en: "Pro yearly" },
        priceUsd: 69,
        interval: "year",
        features: [
          { es: "Todo lo de Pro", en: "Everything in Pro" },
          { es: "Casi 3 meses gratis", en: "Almost 3 months free" },
          { es: "Bloqueás el precio de por vida", en: "Lock in your price for life" },
        ],
      },
    ],
  },

  landing: {
    hero: {
      headline: {
        es: "Un entrenador que se adapta a vos, no al revés.",
        en: "A coach that adapts to you, not the other way around.",
      },
      subheadline: {
        es: "Pulso arma tu plan semanal con IA según tu objetivo, tu equipo y tus lesiones — y lo reajusta cada semana con lo que registrás en cada sesión.",
        en: "Pulso builds your weekly plan with AI around your goal, your equipment and your injuries — then re-tunes it every week from what you log in each session.",
      },
      ctaPrimary: { es: "Armá tu plan gratis", en: "Build your free plan" },
      ctaSecondary: { es: "Ver cómo se adapta", en: "See how it adapts" },
    },
    socialProof: {
      es: "+40.000 sesiones registradas este mes por gente que dejó las planillas.",
      en: "+40,000 sessions logged this month by people who ditched spreadsheets.",
    },
    valueProps: [
      {
        title: { es: "Se adapta a tu rendimiento real", en: "Adapts to your real performance" },
        body: {
          es: "Registrás series, peso y cómo te sentiste. La semana siguiente Pulso sube, mantiene o baja la carga — sin que toques nada.",
          en: "You log sets, weight and how it felt. Next week Pulso pushes, holds or backs off the load — without you touching a thing.",
        },
      },
      {
        title: { es: "Respeta tus lesiones", en: "Respects your injuries" },
        body: {
          es: "Decile qué te molesta una vez. Pulso evita los movimientos riesgosos y los reemplaza por variantes seguras, no por excusas.",
          en: "Tell it what bothers you once. Pulso routes around risky movements with safe variations, never excuses.",
        },
      },
      {
        title: { es: "Hecho para el gimnasio, no para el escritorio", en: "Built for the gym, not the desk" },
        body: {
          es: "App móvil rápida: abrís, ves la sesión de hoy, registrás entre series y listo. Tu racha te sigue empujando.",
          en: "Fast mobile app: open it, see today's session, log between sets, done. Your streak keeps pushing you.",
        },
      },
    ],
    faq: [
      {
        q: { es: "¿Necesito ir a un gimnasio?", en: "Do I need a gym?" },
        a: {
          es: "No. Decinos qué equipo tenés — incluso si es 'nada' — y Pulso arma un plan con lo que haya, en casa o en el gym.",
          en: "No. Tell us what equipment you have — even if it's 'none' — and Pulso builds a plan around it, at home or at the gym.",
        },
      },
      {
        q: { es: "¿Es seguro si tengo una lesión?", en: "Is it safe if I have an injury?" },
        a: {
          es: "Pulso evita los ejercicios contraindicados para tu lesión y baja la carga si reportás dolor. Aun así, no reemplaza el consejo de un profesional de salud.",
          en: "Pulso avoids exercises contraindicated for your injury and de-loads if you report pain. Even so, it doesn't replace advice from a health professional.",
        },
      },
      {
        q: { es: "¿Puedo cancelar cuando quiera?", en: "Can I cancel anytime?" },
        a: {
          es: "Sí, en un toque y sin preguntas. El plan gratis no caduca nunca.",
          en: "Yes, one tap, no questions. The free plan never expires.",
        },
      },
    ],
    finalCta: {
      headline: { es: "Tu próxima semana de entrenamiento, lista en un minuto.", en: "Your next training week, ready in a minute." },
      button: { es: "Empezar gratis", en: "Start free" },
    },
  },

  compliance: {
    notices: [
      "Pulso no es un servicio médico. Consultá a un profesional de salud antes de empezar un programa de ejercicio, sobre todo si tenés una condición preexistente.",
      "Detené el ejercicio y buscá atención médica si sentís dolor agudo, mareos o falta de aire.",
    ],
    ageGate: 16,
  },

  platforms: { web: true, mobile: true, admin: true },
  infra: { deploy: "fly", region: "gru", emailProvider: "resend" },
}

export default pulso
