/**
 * EXAMPLE — a recipes SaaS generated by Puglit.
 * Showcases: content-blog with AI CHEF PERSONAS + freemium + AI layer.
 */
import type { DomainConfig } from "../domain.config"

const recipes: DomainConfig = {
  identity: {
    name: "Sazón",
    tagline: "Tu cocina, con chefs que escriben para vos",
    domain: "example-recipes.com",
    languages: ["es", "en"],
    brandColor: "#E8552D",
    targetMarkets: ["PE", "MX", "AR", "ES", "US"],
  },

  modules: {
    payments: true,
    emailLifecycle: true,
    contentBlog: true,   // ← the magazine-with-authors engine (the recipe blog)
    aiLayer: true,
    profiling: true,     // learn taste preferences → recommend recipes
    growth: true,
  },

  entities: [
    {
      name: "Recipe",
      plural: "Recipes",
      public: true,
      searchable: true,
      fields: [
        { name: "title", type: "text", required: true },
        { name: "slug", type: "slug", unique: true },
        { name: "cuisine", type: "enum", enumValues: ["peruana", "mexicana", "italiana", "vegana", "asiática"] },
        { name: "ingredients", type: "json", note: "array of {item, qty, unit}" },
        { name: "steps", type: "json", note: "ordered array of strings" },
        { name: "minutes", type: "int" },
        { name: "servings", type: "int" },
        { name: "body", type: "longtext", aiGenerated: true, note: "narrative written in the author's voice" },
        { name: "authorId", type: "ref", ref: "Author" },
        { name: "coverUrl", type: "url" },
        { name: "vegan", type: "bool" },
      ],
    },
    {
      name: "Author",
      public: true,
      fields: [
        { name: "name", type: "text", required: true },
        { name: "bio", type: "longtext" },
        { name: "avatarUrl", type: "url" },
      ],
    },
    {
      name: "SavedRecipe",
      ownedByUser: true,
      fields: [{ name: "recipeId", type: "ref", ref: "Recipe", required: true }],
    },
  ],

  content: {
    contentType: "recipe",
    cadence: "morning-noon-evening",
    autoPublishSocial: true,
    authors: [
      { name: "Doña Ramona", voice: "abuela cálida, sabia, anécdotas de cocina criolla", expertise: "cocina peruana tradicional" },
      { name: "Chef Aoki", voice: "preciso, minimalista, técnico", expertise: "cocina asiática y fusión" },
      { name: "Valentina Greens", voice: "fresca, optimista, eco-consciente", expertise: "cocina vegana y saludable" },
    ],
  },

  monetization: {
    model: "freemium",
    providers: ["stripe"],
    plans: [
      { id: "free", priceUsd: 0, features: ["recetas públicas", "guardar 10 recetas"] },
      { id: "pro", priceUsd: 6, interval: "month", features: ["recetas ilimitadas", "planificador semanal con IA", "lista de compras automática"] },
    ],
  },

  compliance: {
    notices: ["Información nutricional referencial.", "Verificá alérgenos antes de cocinar."],
  },

  platforms: { web: true, mobile: true, admin: true },
  infra: { deploy: "fly", region: "gru", emailProvider: "resend" },
}

export default recipes
