/**
 * Puglit — materialize-config.mjs
 * Writes spine/domain.config.ts from an examples/<slug>.config.ts so the spine
 * can be built/deployed for any example without a circular import. It rewrites
 * the example's `../domain.config` type import to the local `./domain-types`
 * and re-exports the types (spine code imports them from "@/domain.config").
 *
 * Usage:  node scripts/materialize-config.mjs <slug>     (e.g. mesa, pulso)
 */
import { readFileSync, writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, join } from "node:path"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const slug = process.argv[2]
if (!slug) {
  console.error("usage: node scripts/materialize-config.mjs <slug>")
  process.exit(1)
}

const src = readFileSync(join(root, "examples", `${slug}.config.ts`), "utf8")
  // point type imports at the local types file (no circular ../domain.config)
  .replace(/from\s+["']\.\.\/domain\.config["']/g, 'from "./domain-types"')

const out = `// AUTO-GENERATED by scripts/materialize-config.mjs from examples/${slug}.config.ts
// Edit the example, not this file. Re-run the script to refresh.
export * from "./domain-types"
${src}`

writeFileSync(join(root, "spine", "domain.config.ts"), out)
console.log(`spine/domain.config.ts ← examples/${slug}.config.ts`)
