-- Promiedos — catalog seed (generated by Puglit's Data Ingestion agent).
-- Real-world reference data so the app works on first run; refresh via app/api/cron/refresh.

-- seed
INSERT INTO tournaments (id, name, start_date, end_date, current_round) VALUES
(1, 'Liga Profesional de Fútbol', CURRENT_DATE - INTERVAL '2 months', CURRENT_DATE + INTERVAL '2 months', 10),
(2, 'Copa Argentina', CURRENT_DATE - INTERVAL '1 month', CURRENT_DATE + INTERVAL '1 month', 5),
(3, 'Primera Nacional', CURRENT_DATE - INTERVAL '3 months', CURRENT_DATE + INTERVAL '3 months', 15);

INSERT INTO matches (id, date, team_home, team_away, score_home, score_away) VALUES
(1, NOW() - INTERVAL '2 days', 'River Plate', 'Boca Juniors', 2, 1),
(2, NOW() - INTERVAL '1 day', 'Racing Club', 'Independiente', 1, 1),
(3, NOW(), 'San Lorenzo', 'Vélez Sarsfield', 0, 0),
(4, NOW() + INTERVAL '2 hours', 'Talleres', 'Lanús', 1, 2),
(5, NOW() + INTERVAL '1 day', 'Rosario Central', 'Newell''s Old Boys', 3, 2),
(6, NOW() + INTERVAL '3 days', 'Argentinos Juniors', 'Gimnasia', 0, 0),
(7, NOW() + INTERVAL '5 days', 'Estudiantes', 'Huracán', 2, 0),
(8, NOW() + INTERVAL '7 days', 'Colón', 'Defensa y Justicia', 1, 1);

INSERT INTO standings (id, tournament_id, team_name, points, matches_played) VALUES
(1, 1, 'River Plate', 25, 10),
(2, 1, 'Boca Juniors', 20, 10),
(3, 1, 'Racing Club', 18, 10),
(4, 1, 'Independiente', 15, 10),
(5, 1, 'San Lorenzo', 22, 10),
(6, 1, 'Vélez Sarsfield', 17, 10),
(7, 1, 'Talleres', 19, 10),
(8, 1, 'Lanús', 21, 10),
(9, 1, 'Rosario Central', 16, 10),
(10, 1, 'Newell''s Old Boys', 14, 10);

INSERT INTO goal_scorers (id, match_id, player_name, goals) VALUES
(1, 1, 'Julián Álvarez', 2),
(2, 1, 'Carlos Tevez', 1),
(3, 2, 'Lisandro López', 1),
(4, 2, 'Silvio Romero', 1),
(5, 5, 'Marco Ruben', 3),
(6, 5, 'Ignacio Scocco', 2);
