-- DuelDeck — catalog seed (generated by Puglit's Data Ingestion agent).
-- Real-world reference data so the app works on first run; refresh via app/api/cron/refresh.

-- seed
INSERT INTO cards (name, atk, def, atributo, tipo, level, image_url) VALUES
('Dark Magician', 2000, 1500, 'Dark', 'Monster', 7, 'https://example.com/dark-magician.png'),
('Blue-Eyes White Dragon', 2500, 2000, 'Light', 'Monster', 8, 'https://example.com/blue-eyes.png'),
('Yugi Muto', 1000, 1000, 'Dark', 'Monster', 6, 'https://example.com/yugi.png'),
('Red-Eyes Black Dragon', 2500, 2000, 'Fire', 'Monster', 9, 'https://example.com/red-eyes.png'),
('Slifer the Sky Dragon', 3000, 2500, 'Dark', 'Monster', 10, 'https://example.com/slifer.png'),
('Chaos Sorcerer', 2000, 1500, 'Light', 'Spell', 6, 'https://example.com/chaos-sorcerer.png'),
('Dark Magician Girl', 1500, 1000, 'Dark', 'Monster', 7, 'https://example.com/dark-magician-girl.png'),
('Summoned Skull', 2000, 1500, 'Light', 'Monster', 8, 'https://example.com/summoned-skull.png'),
('Exodia the Forbidden One', 3000, 2500, 'Dark', 'Monster', 9, 'https://example.com/exodia.png'),
('Black Luster Soldier - Envoy of the Beginning', 2500, 2000, 'Dark', 'Monster', 7, 'https://example.com/black-luster-soldier.png'),
('Chaos Emperor Dragon - Envoy of the End', 3000, 2500, 'Dark', 'Monster', 10, 'https://example.com/chaos-emperor-dragon.png');
INSERT INTO card_images (card_id, url) VALUES
(1, 'https://example.com/dark-magician.png'),
(2, 'https://example.com/blue-eyes.png'),
(3, 'https://example.com/yugi.png'),
(4, 'https://example.com/red-eyes.png'),
(5, 'https://example.com/slifer.png'),
(6, 'https://example.com/chaos-sorcerer.png'),
(7, 'https://example.com/dark-magician-girl.png'),
(8, 'https://example.com/summoned-skull.png'),
(9, 'https://example.com/exodia.png'),
(10, 'https://example.com/black-luster-soldier.png'),
(11, 'https://example.com/chaos-emperor-dragon.png');
INSERT INTO matches (match_id, player1_name, player2_name, score, date) VALUES
('M001', 'Yugi Muto', 'Joey Wheeler', 10, NOW()),
('M002', 'Seto Kaiba', 'Mai Valentine', 5, NOW() + INTERVAL '2 hours'),
('M003', 'Tristan Taylor', 'Tea Gardner', 8, NOW() - INTERVAL '1 day');
INSERT INTO decks (deck_id, card_ids, quantity) VALUES
(1, ARRAY['1','2','3'], 3),
(2, ARRAY['4','5','6'], 2),
(3, ARRAY['7','8','9'], 1);
