export * from "./domain-types"
import type { DomainConfig } from "./domain-types"

// Generated by Puglit (https://puglit.com). Edit this file — the whole app follows.
const config: DomainConfig = {
  "infra": {
    "deploy": "fly",
    "emailProvider": "resend"
  },
  "landing": {
    "faq": [
      {
        "a": "I'm still alive is free.",
        "q": "How much does it cost?"
      },
      {
        "a": "Yes — one click, no questions.",
        "q": "Can I cancel anytime?"
      },
      {
        "a": "Yes. Your data is yours and you can export it.",
        "q": "Do I own my data?"
      }
    ],
    "hero": {
      "headline": "it will ensure your family gets a farewell",
      "ctaPrimary": "Get started",
      "subheadline": "A simple way to ensure your final messages reach the people you care about.",
      "ctaSecondary": "See pricing"
    },
    "finalCta": {
      "button": "Get started",
      "headline": "Ready to try I'm still alive?"
    },
    "valueProps": [
      {
        "body": "Built into I'm still alive from day one — no glue code.",
        "title": "it will ensure your family gets a farewell"
      }
    ],
    "socialProof": "Made for 40+ year people."
  },
  "modules": {},
  "entities": [
    {
      "name": "Message",
      "fields": [
        {
          "name": "content",
          "type": "longtext",
          "required": true
        },
        {
          "name": "recipient_email",
          "type": "email",
          "required": true
        },
        {
          "name": "scheduled_date",
          "type": "datetime",
          "required": true
        },
        {
          "name": "is_delivered",
          "type": "bool",
          "required": false
        }
      ],
      "plural": "Messages",
      "ownedByUser": true
    },
    {
      "name": "User",
      "fields": [
        {
          "name": "username",
          "type": "text",
          "required": true
        },
        {
          "name": "email",
          "type": "email",
          "required": true
        },
        {
          "name": "created_at",
          "type": "datetime",
          "required": true
        },
        {
          "name": "is_active",
          "type": "bool",
          "required": true
        }
      ],
      "plural": "Users",
      "ownedByUser": true
    }
  ],
  "identity": {
    "name": "I'm still alive",
    "domain": "i-m-still-alive.app",
    "tagline": "A simple way to ensure your final messages reach the people you care about.",
    "languages": [
      "en",
      "es"
    ],
    "brandColor": "#6A0DAD",
    "targetMarkets": []
  },
  "platforms": {
    "web": true,
    "admin": true
  },
  "monetization": {
    "model": "free",
    "plans": [
      {
        "id": "free",
        "features": [
          "Core features",
          "Community support"
        ],
        "priceUsd": 0
      }
    ],
    "providers": [
      "stripe"
    ]
  }
}

export default config
