export * from "./domain-types"
import type { DomainConfig } from "./domain-types"

// Generated by Puglit (https://puglit.com). Edit this file — the whole app follows.
const config: DomainConfig = {
  "infra": {
    "deploy": "fly",
    "emailProvider": "resend"
  },
  "engine": {
    "kind": "ai",
    "output": "the product's core result",
    "description": "AI travel itineraries built around your style and budget"
  },
  "landing": {
    "faq": [
      {
        "a": "Start free, then $7/mo. Cancel anytime.",
        "q": "How much does it cost?"
      },
      {
        "a": "Yes — one click, no questions.",
        "q": "Can I cancel anytime?"
      },
      {
        "a": "Yes. Your data is yours and you can export it.",
        "q": "Do I own my data?"
      }
    ],
    "hero": {
      "headline": "A full trip plan in minutes",
      "ctaPrimary": "Get started",
      "subheadline": "AI travel itineraries built around your style and budget",
      "ctaSecondary": "See pricing"
    },
    "finalCta": {
      "button": "Get started",
      "headline": "Ready to try Senda?"
    },
    "valueProps": [
      {
        "body": "Built into Senda from day one — no glue code.",
        "title": "A full trip plan in minutes"
      },
      {
        "body": "It just works, so you can focus on your users.",
        "title": "Fits your budget and pace"
      },
      {
        "body": "Reliable, secure and ready to scale.",
        "title": "Maps, bookings and tips in one place"
      }
    ],
    "socialProof": "Made for independent travelers who hate planning."
  },
  "modules": {
    "geo": true,
    "aiLayer": true,
    "payments": true,
    "emailLifecycle": true
  },
  "entities": [
    {
      "name": "Itinerary",
      "fields": [
        {
          "name": "destination",
          "type": "text",
          "required": true
        },
        {
          "name": "budget",
          "type": "float",
          "required": true
        },
        {
          "name": "travel_date",
          "type": "date",
          "required": true
        },
        {
          "name": "preferences",
          "type": "json",
          "required": false
        }
      ],
      "plural": "Itineraries",
      "ownedByUser": true
    },
    {
      "name": "Booking",
      "fields": [
        {
          "name": "itinerary_id",
          "type": "int",
          "required": true
        },
        {
          "name": "service_type",
          "type": "enum",
          "required": true,
          "enumValues": [
            "flight",
            "hotel",
            "car_rental",
            "activity"
          ]
        },
        {
          "name": "confirmation_number",
          "type": "text",
          "required": true
        },
        {
          "name": "booking_date",
          "type": "datetime",
          "required": true
        }
      ],
      "plural": "Bookings",
      "ownedByUser": true
    },
    {
      "name": "Tip",
      "fields": [
        {
          "name": "itinerary_id",
          "type": "int",
          "required": true
        },
        {
          "name": "content",
          "type": "longtext",
          "required": true
        },
        {
          "name": "source_url",
          "type": "url",
          "required": false
        },
        {
          "name": "created_at",
          "type": "datetime",
          "required": true
        }
      ],
      "plural": "Tips",
      "ownedByUser": true
    }
  ],
  "identity": {
    "name": "Senda",
    "domain": "senda.app",
    "tagline": "AI travel itineraries built around your style and budget",
    "languages": [
      "en",
      "es"
    ],
    "brandColor": "#0EA5E9",
    "targetMarkets": []
  },
  "platforms": {
    "web": true,
    "admin": true
  },
  "monetization": {
    "model": "freemium",
    "plans": [
      {
        "id": "free",
        "features": [
          "Core features",
          "Community support"
        ],
        "priceUsd": 0
      },
      {
        "id": "pro",
        "features": [
          "A full trip plan in minutes",
          "Fits your budget and pace",
          "Maps, bookings and tips in one place",
          "Priority support"
        ],
        "interval": "month",
        "priceUsd": 7,
        "highlight": true
      },
      {
        "id": "anual",
        "features": [
          "Everything in Pro",
          "2 months free"
        ],
        "interval": "year",
        "priceUsd": 70
      }
    ],
    "providers": [
      "stripe"
    ]
  }
}

export default config
