import { NextRequest, NextResponse } from "next/server"
import { getAuthUser } from "@/lib/auth"
import { pool } from "@/lib/db"

// Deterministic "near me" (generated by Puglit): offers at branches within radius
// whose program is one the user owns, ordered by distance (Haversine). Coordinates
// come from ?lat/?lng or the user's saved location.
export async function GET(request: NextRequest) {
  const u = await getAuthUser(request)
  if (!u) return NextResponse.json({ error: "unauthorized" }, { status: 401 })
  const sp = new URL(request.url).searchParams
  const latP = sp.get("lat") ?? sp.get("latitude"), lngP = sp.get("lng") ?? sp.get("longitude")
  let lat = latP != null && latP !== "" ? Number(latP) : NaN
  let lng = lngP != null && lngP !== "" ? Number(lngP) : NaN
  const radius = Number(sp.get("radius")) || 5
  if (!Number.isFinite(lat) || !Number.isFinite(lng)) {
    const loc = await pool.query("SELECT latitude, longitude FROM user_locations WHERE user_id=$1", [u.userId])
    if (!loc.rows[0]) return NextResponse.json([])
    lat = loc.rows[0].latitude; lng = loc.rows[0].longitude
  }
  const { rows } = await pool.query(
    `SELECT * FROM (
       SELECT o.id AS offer_id, o.*, to_json(m) AS merchant, b.address, b.latitude AS latitude, b.longitude AS longitude, p.name AS program_name,
         (6371 * acos(LEAST(1, cos(radians($1)) * cos(radians(b.latitude)) * cos(radians(b.longitude) - radians($2)) + sin(radians($1)) * sin(radians(b.latitude))))) AS distance_km
       FROM offers o
       JOIN branches b ON b.merchant_id = o.merchant_id
       JOIN merchants m ON m.id = o.merchant_id
       JOIN programs p ON p.id = o.program_id
       WHERE o.program_id IN (SELECT program_id FROM user_memberships WHERE user_id = $3)
     ) t
     WHERE t.distance_km <= $4
     ORDER BY t.distance_km ASC
     LIMIT 100`,
    [lat, lng, u.userId, radius]
  )
  return NextResponse.json(rows)
}
